# -*- coding: utf-8 -*-
import os, json

home = os.path.expanduser('~')
pnc_name = "pettek-nanach-commentary"
base = os.path.join(home, '.openclaw', 'workspace', 'ajew-org', 'public', 'reader')
pnc_dir = os.path.join(base, pnc_name)
src_dir = os.path.join(base, 'likutay-moharan', 'part-2')
commentaries_path = os.path.join(home, '.openclaw', 'workspace', 'ajew-org', 'src', 'data', 'lm-commentaries.json')

torahs = {
    51: {
        "title_en": "Avnei Shayish Tahor / Al Tomru Mayim Mayim — Sheker Damages Eyes and Hashgachah",
        "title_he": "אבני שיש טהור / אל תאמרו מים מים",
        "segs": [
            {
                "beginner": "Rabbi Akiva said to the four who entered the Pardes: 'When you reach the stones of pure marble, do not say water-water,' as the verse says, 'a speaker of falsehoods will not stand before My eyes' (Psalms 101:7). Sheker damages the eyes — physically and spiritually — as in 'eyes that lie' (Isaiah 3:16): when eyes dim they 'lie,' showing things not as they are — making the great seem small or one seem two, the opposite of truth. The eyes dim from tears: 'and the clouds returned after the rain' (Shabbos 151b) — vision follows weeping. Tears are excess of marah-shechorah which the body expels through the eyes. Marah-shechorah draws from impure blood, and impure blood comes from speaking sheker — for it is impossible to speak sheker without first muddying one's blood, and impossible to speak truth without first refining the blood. Speech is the nefesh ('my soul went out as he spoke' — Song of Songs 5:6), and nefesh is the blood ('for the blood is the nefesh' — Leviticus 17:11). So sheker → blood-impurity → marah-shechorah → tears → dim eyes. 'הקטפים מלוח עלי שיח' (Job 30:4) — 'malu'ach' (salt) is the salty waters of tears, brought through 'siach' (speech). 'Al tomru mayim mayim' is therefore a warning against sheker (R. Akiva closes there with 'a speaker of falsehoods'). Sheker is 'mayim mayim' — salty waters: ordinary water quenches thirst, but salty water doesn't quench, only adds thirst upon thirst, until one needs other water to extinguish it. So is sheker called 'mayim mayim.'",
                "intermediate": "**אמר רבי עקיבא: כשאתם מגיעים לאבני שיש טהור, אל תאמרו מים מים** — \"דֹּבֵר שְׁקָרִים לֹא יִכּוֹן לְנֶגֶד עֵינָי\" (תה' קא:ז). **Sheker mazik la-einayim** ba-gashmiyus u-va-ruchaniyus — בחינת \"וּמְשַׂקְּרוֹת עֵינָיִם\" (יש' ג:טז) — k'she-ha-einayim kehos hen meshakros, einan mar'os ha-davar kemo she-hu (gadol-katan; achad-shnayim — heipech ha-emes). Ha-einayim na'asu kehos min ha-dema'os — \"וְשָׁבוּ הֶעָבִים אַחַר הַגֶּשֶׁם\" (שבת קנ\"א:): 'zeh ha-re'us she-holech achar ha-bechi'. **Dema'os min mosrei ha-marah-shechorah**, ha-teva docheh osam la-chutz derech ha-einayim. **Marah-shechorah sho'eves me-akiras ha-damim. Ve-akiras ha-damim al-yedei ha-sheker** — ee-efshar ledaber sheker ad she-ya'achir et damav, ve-emes ee-efshar ledaber ki im k'she-mezakech kodem et ha-damim. Ki **ikar ha-dibur hu ha-nefesh** — \"נַפְשִׁי יָצְאָה בְדַבְּרוֹ\" (שיה\"ש ה:ו) — ve-ha-**nefesh hu ha-dam** — \"כִּי הַדָּם הוּא הַנֶּפֶשׁ\" (וי' יז:יא). Nimtza: sheker → akiras-damim → marah-shechorah → dema'os → einayim kehos. **\"הַקֹּטְפִים מַלּוּחַ עֲלֵי שִׂיחַ\"** (איוב ל:ד) — מלוח = dema'os (mayim meluchim) ha-ba'os al-yedei sichah. Ve-zehu **\"אל תאמרו מים מים\"** = azharah al sheker (ka-asher siyem 'דובר שקרים לא יכון'). \"מים מים\" = bechinas sheker = dema'os mayim meluchim — **ha-shoseh mayim** marveh tzme'ono; ha-shoseh **mayim meluchim** mosif tzima'on al tzima'on, ad she-tzarich lishtos mayim acherim le-chabos tzme'ono. Lachen sheker nikra **\"מים מים.\"**",
                "scholarly": "[T2:51a] חגיגה יד: ארבעה נכנסו לפרדס — \"כשאתם מגיעים לאבני שיש טהור אל תאמרו מים מים\". \"דובר שקרים לא יכון לנגד עיני\" (תה' קא:ז). שקר → עכירת דמים → מ\"ש → דמעות → עינים כהות. \"ומשקרות עינים\" (יש' ג:טז). \"ושבו העבים אחר הגשם\" (שבת קנ\"א:). הדם הוא הנפש (וי' יז:יא); נפשי יצאה בדברו (שיה\"ש ה:ו). \"הקטפים מלוח עלי שיח\" (איוב ל:ד). מים מים = מים מלוחים מוסיפים צמאון."
            },
            {
                "beginner": "The very emergence of sheker — which is ra and tumah — is from distance from the One. Ra is opposition; whatever opposes a person's will is ra. In the One, no opposition applies — only good. The Sages teach (Pesachim 50a): 'On that day Hashem will be one and His Name one — kulo ha-tov ve-ha-meitiv,' for in the One ra has no place. Therefore le-asid lavo: 'a lip of truth will be established forever' (Proverbs 12:19) — for then all will be one, all good. Truth is one — say of a silver vessel that it is a kli kesef and you are right; say it is a kli zahav and you lie. Truth is one alone — only kli kesef, no more. But sheker is many: gold, copper, any name — 'they sought many calculations' (Ecclesiastes 7:29). Le-asid the ra will be nullified, opposition nullified, tears nullified — 'they will not harm' (Isaiah 11:9 — bittul ha-ra), 'and the wolf shall dwell with the lamb, the leopard with the kid' (Isaiah 11:6 — bittul ha-hisnagdus), 'and Hashem Elokim will wipe away tears from every face' (Isaiah 25:8 — bittul ha-dema'os, which are sheker). 'Then Hashem will be one and His Name one' — kulo tov, kulo emes. So tumah will pass: 'and the spirit of impurity I will remove from the earth' (Zechariah 13:2). For all will be one — 'who can produce the pure from the impure? Not one' (Job 14:4): the very anchor of taharah and tumah is from the bechinah of distance from the One.",
                "intermediate": "**Hisha-vus ha-sheker — she-hu ra she-hu tumah — me-chamas ha-richuk me-Echad.** Ra = negdiyus; kol mah she-neged retzono shel adam hu ra. U-va-Echad ein shayach negdiyus ela kulo tov. Ka-asher amru chaza\"l (פסחים נ.): **\"בַּיּוֹם הַהוּא יִהְיֶה ה' אֶחָד...\"** — she-yiheyeh kulo ha-tov ve-ha-meitiv — ki ba-Echad ein shayach ra. Lachen le-asid lavo yu-kayim **\"שְׂפַת אֱמֶת תִּכּוֹן לָעַד\"** (משלי יב:יט) — yiheyeh az kulo Echad, kulo tov. Ki **emes hu Echad**, mashal: kli kesef — k'she-omrim alav 'kli kesef' zehu emes; aval 'kli zahav' — sheker. **Ha-emes Echad** — ee-efshar lomar emes ela 'kli kesef' lo yoter. Aval ha-sheker rabim — efshar lomar zahav, nechoshes, etc. Bechinas **\"בִּקְשׁוּ חֶשְׁבֹּנוֹת רַבִּים\"** (קה' ז:כט). Bishvil zeh le-asid lavo — bittul ha-ra, bittul ha-hisnagdus, bittul ha-dema'os: **\"לֹא יָרֵעוּ\"** (יש' יא:ט) — bittul ha-ra; **\"וְגָר זְאֵב עִם כֶּבֶשׂ וְנָמֵר עִם גְּדִי\"** (שם יא:ו) — bittul ha-hisnagdus; **\"וּמָחָה ה' אֱלֹהִים דִּמְעָה מֵעַל כָּל פָּנִים\"** (שם כה:ח) — bittul ha-dema'os she-hen bechinas sheker (ת\"כב סו:). Az 'יִהְיֶה ה' אחד ושמו אחד' she-hu kulo tov, kulo emes. Az bittul ha-tumah — **\"וְאֶת רוּחַ הַטֻּמְאָה אַעֲבִיר מִן הָאָרֶץ\"** (זכ' יג:ב) — yiheyeh kulo Echad: **\"מִי יִתֵּן טָהוֹר מִטָּמֵא לֹא אֶחָד\"** (איוב יד:ד) — peirush: **ikar achizas ha-taharah ve-ha-tumah hu mi-bechinas richuk me-Echad.**",
                "scholarly": "[T2:51b] שקר/רע/טומאה — מריחוק מאחד. \"שפת אמת תכון לעד\" (משלי יב:יט). \"בקשו חשבונות רבים\" (קה' ז:כט). לעת\"ל: \"לא ירעו\"; \"וגר זאב עם כבש\" (יש' יא); \"ומחה ה' דמעה\" (יש' כה:ח). תיקונים ת\"כב סו:. \"ואת רוח הטומאה אעביר\" (זכ' יג:ב). \"מי יתן טהור מטמא לא אחד\" (איוב יד:ד) — אחיזת הטומאה מריחוק מאחד."
            },
            {
                "beginner": "Before creation, when Creation was still potential, kulo Echad — kulo emes, kulo tov, kulo kodesh. Even the term 'tahor' did not yet apply, for tahor only applies where tumah exists ('and you shall be tahor from all your tumah'). When all is Echad, no 'cheshbonos rabim' apply, which is the root of ra and tumah. Taharah is the mediating point between kodesh and tumah, through which tumah is rectified — bechinas ha-bechirah, the choice that mediates between two. Before creation no bechirah applied — in Echad, no bechirah. When the Holy One brought Creation from potential to actual, taharah immediately came into being — for now there were two: ha-Echad and ha-Beriah; bechirah, taharah, became applicable. Taharah is close to Echad and has not yet reached cheshbonos rabim, which is ra/tumah; yet it is a hint, a sign, of the chain that will reach all the way down to tumah. So the Zohar says: ikar achizas ha-tumah is from sitra de-smola — taharah hints at the existence of tumah and signals its eventual unfolding. Therefore one can rectify tumah back to taharah — for it itself unfolded from taharah. Taharah is bechinas smol, bechinas Levi: 've-tihartah es Bnei Levi' — and Levi is bechinas smol. After Creation: through Hashem's hashgachah, even after creation everything is in unity with Him. Ra suckles from 'achorei kasfa' — distant from the One. Through emes — Hashem's hashgachah is upon him: 'My eyes are upon the faithful of the land' (Psalms 101:6); through sheker — He removes hashgachah: 'a speaker of falsehoods will not stand before My eyes' (101:7) — ein chiyuso ela me-achorei kasfa. So R. Akiva said: 'when you reach avnei shayish tahor' — yesh, post-emergence, where 'tahor' applies — 'al tomru mayim mayim': do not utter sheker, which removes hashgachah. Want av u-ven k'echad? Through emes, Hashem's hashgachah is upon you, and all is Echad as before creation.",
                "intermediate": "**Kodem ha-beriah — kulo Echad, kulo emes, kulo tov, kulo kodesh.** Afilu shem 'tahor' lo hayah shayach lomar, ki tahor eino shayach ela k'she-yesh tumah (\"וטהרתם מכל טמאותיכם\"). U-va-Echad ein cheshbonos rabim. **Taharah = bechinas ha-mema-tza bein ha-kodesh ve-ha-tumah** — bechinas **ha-bechirah** — ha-mema-tza bein shtei devarim. Kodem ha-beriah ein shayach bechirah — ba-Echad ein bechirah. K'she-hotzi ha-Kadosh Baruch Hu et ha-beriah me-ha-koach el ha-po'el — niskvah tekhef bechinas ha-taharah, ki hayu shtei devarim: ha-Echad ve-ha-beriah. Az shayach bechirah, she-hu bechinas taharah — mema-tza bein ha-Echad (samuch lo, va-adayin lo higi'a le-cheshbonos rabim she-hu ra/tumah) — ach hu **roshem ve-siman al ha-hishtalshelus** she-yuchal le-hishtalshel ad she-yiheyeh ra ve-tumah. Lachen ba-Zohar (בר' מח. u-bekhamah mekomos): **ikar achizas ha-tumah mi-sitra de-smola** — ki ha-taharah meramezet she-yesh tumah. U-le-fi-chach efshar le-zakech ve-le-ha'alos ha-tumah la-taharah — ki hi atzmah hishtalsheh me-taharah: \"וטהרתם מכל טמאותיכם\". **Taharah = smol = Levi** — \"וְטִהַרְתָּ אֶת בְּנֵי הַלְוִיִּם\" (במ' ח); ve-Levi smol ka-yadua. Lachen ikar achizas ha-tumah mi-bechinas smol. Kol zeh nimshach mi-bechinas **achar ha-beriah** — k'she-yatza ha-beriah me-koach el po'el ve-hayu shtei bechinos: ha-Echad ve-ha-beriah. **Ve-al-yedei hashgachas Hashem yisborach — afilu achar ha-pe'ulah, kol ha-devarim be-achdus imo.** Ha-ra yonek **mi-she'eiras ha-hashgachah** — me-achorei kasfa (זוה\"ק חוקת קפד:). Ve-al-yedei **emes** hashgachas Hashem — \"עֵינַי בְּנֶאֶמְנֵי אֶרֶץ\" (תה' קא:ו); ve-al-yedei **sheker** mesir mimenu hashgachah — \"דֹּבֵר שְׁקָרִים לֹא יִכּוֹן לְנֶגֶד עֵינָי\" (קא:ז) ve-ein chiyuso ela me-achorei kasfa. **Mi she-rotzeh she-yiheyeh achar ha-yeshus ve-ha-pe'ulah kulo Echad — av u-ven k'echad — yishmor atzmo me-sheker.** Ve-zehu de-amar Rabi Akiva: **\"אבני שיש טהור\"** = bechinas achar ha-pe'ulah (yesh, taharah). **\"אבני\"** = av u-ven k'chada (kodem ha-beriah, kulo Echad). Im tirtze le-hagi'a 'shayish tahor' la-'avnei' — **\"אל תאמרו מים מים\"** (sheker), she-na-emar 'דובר שקרים לא יכון לנגד עיני'. Al-yedei emes — hashgachah — kulo Echad, kemo kodem ha-beriah. Ve-al ken sechar olam ha-ba: **\"עַיִן לֹא רָאָתָה אֱלֹהִים זוּלָתְךָ\"** (יש' סד:ג; ברכ' לד:) — me-achar she-yiheyeh kulo Echad, lo yiheyeh ayin she-tir'eh — rak 'אֱלֹהִים זוּלָתְךָ'.",
                "scholarly": "[T2:51c] קודם הבריאה — אחד; אז לא שייך 'טהור' (\"וטהרתם מטומאותיכם\" — יחז' לו:כה). טהרה = ממוצע = בחירה. תחילת אחיזת הטומאה: זוה\"ק בר' מח.; חוקת קפד:; טהרה = שמאל = לוי (במ' ח, \"וטהרת את בני הלויים\"). \"איש לא ראתה אלהים זולתך\" (יש' סד:ג; ברכ' לד:). אבני = אב ובן כחדא (קודם הבריאה); שיש טהור = אחר הפעולה (יש)."
            },
            {
                "beginner": "And so sheker damages the eyes specifically — for through sheker one removes the hashgachah of Hashem's eyes; the eyes are bechinas hashgachah. Sheker is drawn from richuk-me-Echad, the very root of tumah, ra. Sheker pogems hashgachah and removes Hashem's hashgachah from one. Through hashgachah, all is Echad — after creation as before creation; through sheker, one pogems in Echad — sheker is rachok mi-Echad. So sheker mesalek hashgachah, and separates (chas ve-shalom) achar-ha-beriah from kodem-ha-beriah, the very anchor of tumah. But through emes — kulo Echad, kulo tov — one draws Hashem's hashgachah, and all is Echad, after creation included in before creation. This is what R. Akiva said: 'al tomru mayim mayim' — and through emes you reach 'avnei shayish tahor' as 'av u-ven ke-Echad,' and the maamar links its beginning to its end and its end to its beginning — understand well.",
                "intermediate": "**U-vishvil zeh ha-sheker mazik la-einayim** — ki al-yedei sheker mesalek hashgachas einei Hashem yisborach, **u-fogem ba-einayim she-hen bechinas hashgachah**. Ha-sheker nimshach me-richuk-me-Echad, she-misham ikar achizas ha-tumah she-hu ha-ra she-hu ha-sheker. U-mi-chamas zeh be-atzmo, **pogem al-yedei sheker ba-hashgachah** u-mesalek hashgachas Hashem mi-meilav. Ki **al-yedei hashgachas Hashem ha-kol Echad** — achar ha-beriah kemo kodem ha-beriah. **Ve-al-yedei sheker pogem ba-Echad**, ki ha-sheker rachok mi-Echad. **U-mafrid (chas ve-shalom) achar-ha-beriah mi-kodem-ha-beriah, she-misham ikar achizas ha-tumah.** Aval **al-yedei emes** — bechinas kulo Echad, kulo tov — al-yedei zeh **mamshich hashgachas Hashem**, ve-az ha-kol Echad — ki al-yedei hashgachah nichlal achar-ha-beriah be-kodem-ha-beriah. Ve-zehu '**אמר רבי עקיבא**' kol ha-na\"l. Ve-ba-zeh mekasher ha-ma'amar zeh heitev: **techilaso be-sofo, ve-sofo bi-techilaso, ve-chen be-emtza'iso — ve-haven heitev.**",
                "scholarly": "[T2:51d] שקר → סילוק השגחה → פוגם בעיניים. אמת → השגחה → איחוד אחר ולפני הבריאה. סוף המאמר: \"תחילתו בסופו וסופו בתחילתו ובאמצעו\" — חתימה הקושרת את כל הפרקים."
            }
        ]
    },
    52: {
        "title_en": "Why Kushyos Are Difficult on the Tzaddikim",
        "title_he": "מה שקשה קשיות על הצדיקים",
        "segs": [
            {
                "beginner": "That kushyos are difficult on the tzaddikim is not by accident — it must be so. The tzaddikim resemble their Creator, as is taught. Just as kushyos are difficult on Hashem yisborach, so it is necessarily difficult to ask kushyos on the tzaddik — because he resembles Him.",
                "intermediate": "**Mah she-kashe kushyos al ha-tzaddikim — zehu mukhrach li-hyos.** Ki **ha-tzaddikim mis-damim le-Yotzram**, ka-mu-vah, **u-ke-mo she-kashe kushyos al Hashem yisborach, ke-mo chen be-hechrach she-yiheyeh kashe kushyos al ha-tzaddik** — ki hu mis-dameh elav yisborach.",
                "scholarly": "[T2:52a] קשיות על הצדיק — מתדמה ליוצרו. עי' מגלה עמוקות; מ\"מ; שיש\"ק. \"כי המכון לפרצוף אדמה דמיתי לכבודי\" — צדיק = דיוקנו של הקב\"ה."
            },
            {
                "beginner": "About kushyos on Hashem yisborach, the Rebbe used to say: on the contrary, this is precisely how it should be — that kushyos remain on Hashem; this is fitting and beautiful for Him according to His greatness and exaltedness. From the very essence of His greatness — that He is exalted high above our daas — it is impossible to grasp His conduct with our intellect. Therefore there must be kushyos on Him; this is fitting and beautiful for the Borei: that He be exalted and elevated above our daas, through which the kushyos are difficult. Were His conduct entirely accessible to the obligations of our daas, then chas ve-shalom His daas would be like our daas.",
                "intermediate": "U-ve-inyan ha-kushyos she-kashe al Hashem yisborach **margelah be-fimo lomar: aderaba — kakh ra'ui li-hyos dika she-yi-hyu kushyos al Hashem yisborach, ve-kakh na'eh ve-yafeh lo yisborach lefi gadlaso ve-romemuso.** Ki **me-otzem gadlaso ve-romemuso** she-hu meromam me'od mi-da'aseinu — al ken be-vadai ee-efshar she-navin u-nasig be-sichleinu hanhagaso yisborach. Ve-al ken **be-hechrach she-yi-hyu alav yisborach kushyos** — ki kakh na'eh ve-yafeh la-Borei yisborach she-yi-hyeh meromam ve-nisa mi-da'aseinu — she-al-yedei zeh kashe ha-kushyos. **Ve-im hayah hanhagaso ke-fi chiyuv da'aseinu — az hayah, chas ve-shalom, da'ato ke-da'aseinu.**",
                "scholarly": "[T2:52b] \"כך נאה ויפה\" — קושיא היא תוצאת הרוממות. אם היה כפי שכלנו → ח\"ו דעתו כדעתנו. עי' לק\"מ ח\"א ס\"ד (מקיפי המוח); מ\"מ \"מח\"ק לא קומ\"ה\"."
            }
        ]
    },
    53: {
        "title_en": "Yikras HaMachshavah; Chochmah Builds Buildings",
        "title_he": "גודל יקרת המחשבה",
        "segs": [
            {
                "beginner": "The Rebbe said: 'The great preciousness of machshavah has just become known to me now.' Machshavah is exceedingly, exceedingly precious — actually whole, real things are made from it, things that endure for as long as the worlds endure, as long as Hashem… and so on. Chochmah is even more precious: machshavah is what merely rises to one's thought; chochmah is what builds, with one's chochmah, structures with one's intellect — and is very precious. The principle: it must be be-emes. Even a simple peshat one is mechadesh is itself a great thing — and must also be be-emes. And the opposite: when not be-emes, things are likewise produced from it — to the contrary.",
                "intermediate": "**גודל יקרת המחשבה נודע לי עתה** — ki **ha-machshavah yekarah me'od me'od**, she-na'aseh mimenah **devarim shleimim mamash**, she-yesh la-hem **kiyum kol ha-yamim she-yiskayemu ha-olamos**, kol zeman asher Hashem yisborach... ve-chu'. **Ve-chochmah yekar yoter** — ki machshavah hi mah she-oleh al machshavto bilvad, **ve-chochmah hi she-boneh be-chochmaso binyanim be-sichlo** — ve-hu yakar me'od. **Ve-ikar ha-davar — she-yiheyeh be-emes.** Va-afilu peshat she-mechadshin — gam-ken davar gadol me'od, ve-tzarich she-yiheyeh be-emes. **Ve-gam le-heipech — k'she-hu be-lo emes na'aseh mimenah gam-ken devarim le-heipech.**",
                "scholarly": "[T2:53] יקרות המחשבה והחכמה. \"דברים שלמים ממש\". עיקר: באמת. שקר במחשבה → דברים להפך. עי' לק\"מ ח\"א מ\"ט (קוצר רוח); ח\"ב ה' (יקרות הזמן והתפילה)."
            }
        ]
    },
    54: {
        "title_en": "Bechirah for the Israelite — Avodah in Every Single Thing",
        "title_he": "הבחירה ביד האדם לעשות כרצונו",
        "segs": [
            {
                "beginner": "Bechirah is in the hand of a person to do as he wishes — and even more, all things are in the hand of the Israelite person to conduct everything as he wishes, as his bechirah. For with Yisrael there is bechirah be-yadam over every single thing in the world. Among others there are matters in which they are mukhrachim, compelled. But by an Israelite, every single thing he does — even traveling somewhere or the like — has avodah in it; therefore he has bechirah over all.",
                "intermediate": "**Ha-bechirah be-yad ha-adam la'asos ki-rtzono.** Va-afilu kol ha-devarim — **ha-kol be-yad ha-ish ha-Yisre'eli le-his-naheg ha-kol ki-rtzono ki-vchiraso**. Ki **be-yad Yisrael yesh bechirah be-yadam al kol davar she-ba-olam**. Ki etzel acherim yesh devarim she-hem mukhrachim ba-hem, aval **etzel ish ha-Yisre'eli — kol davar va-davar she-hu oseh** (kegon li-nso'a le-eizeh makom ve-cha-yotzei) — **yesh bo avodah, ve-al-ken yesh lo bechirah al ha-kol.**",
                "scholarly": "[T2:54] בחירה לישראל בכל דבר. הבדל בין ישראל לאומות העולם — אצלם מוכרחים, אצלנו עבודה ובחירה. עי' לק\"מ ח\"א רס\"א (בחירה); ח\"ב ז' (איש ישראלי)."
            }
        ]
    },
    55: {
        "title_en": "Revach HaOlam HaZeh — Profit Without One's Own Expense",
        "title_he": "ריוח העולם הזה אין לשער",
        "segs": [
            {
                "beginner": "The revach of olam ha-zeh cannot be measured: how much a person can profit in this world without having to spend from his own resources — what they call in Yiddish 'oys-lag' (no out-of-pocket cost). Only from what the Borei yisborach has prepared in front of him, he can extend his hand and gain very much. 'Ayin lo ra'asah'.",
                "intermediate": "**Revach ha-olam ha-zeh ein le-sha'er** — dehaynu **mah she-ha-adam yachol le-har-vi'ach ba-olam ha-zeh ve-ein tzarich al-zeh hotza'os mi-shelo**, she-korin **'אויש לאג'** (oys-lag), **rak mi-mah she-heichin lefanav ha-Borei yisborach yachol le-harchiv yado u-le-har-vi'ach harbeh me'od.** \"עַיִן לֹא רָאָתָה...\" (יש' סד:ג).",
                "scholarly": "[T2:55] ריוח העוה\"ז ללא הוצאות (\"אויש לאג\"). \"עין לא ראתה\" (יש' סד:ג; ברכות לד:). הקב\"ה מכין לפני האדם, רק יש להרחיב יד."
            }
        ]
    },
    56: {
        "title_en": "Lev Yisre'eli Is Mekomo Shel Olam — Place Does Not Apply",
        "title_he": "כשיש להאדם לב, אין שייך אצלו מקום כלל",
        "segs": [
            {
                "beginner": "When a person has a lev (heart), makom does not apply to him at all — on the contrary, he is the makom of the world. For Elokus is in the lev: 'Tzur levavi' (Psalms 73:26). And of Hashem yisborach it is said 'hineh makom iti' (Exodus 33:21) — He is the makom of the world, and the world is not His makom (Rashi; Bereshis Rabbah). One who has a lev Yisre'eli is therefore not fit to say 'this place is not good before me' — for makom does not apply to him at all; on the contrary, he is the makom of the world, and the world is not his makom.",
                "intermediate": "**K'she-yesh la-adam lev — ein shayach etzlo makom klal** — ki **aderaba, hu mekomo shel olam.** Ki **ha-Elokus ba-lev** — \"צוּר לְבָבִי\" (תה' עג:כו). Ve-etzel Hashem yisborach ne'emar **\"הִנֵּה מָקוֹם אִתִּי\"** (שמ' לג:כא) — she-hu mekomo shel olam, ve-ein ha-olam mekomo (רש\"י שם; ב\"ר שם). **Nimtza, mi she-yesh lo lev Yisre'eli — ein ra'ui lo lomar she-makom zeh ein tov le-fanav** — ki ein shayach etzlo makom klal; aderaba, hu mekomo shel olam, ve-ein ha-olam mekomo.",
                "scholarly": "[T2:56] לב = אלקות (\"צור לבבי\" תה' עג:כו). \"הנה מקום אתי\" (שמ' לג:כא) — מקומו של עולם; ב\"ר סח:ט. ישראלי לא יאמר 'מקום זה לא טוב לי'."
            }
        ]
    },
    57: {
        "title_en": "Tzaddik Gadol's Chiddushim Elevate the Ketanim — Even Bilaam",
        "title_he": "כשצדיק גדול אמתי מגלה תורה",
        "segs": [
            {
                "beginner": "When a great true tzaddik reveals Torah — wondrous and awesome chiddushim — it is a benefit to ketanim be-ma'alah, lesser ones in stature, for through this the katan is elevated, and everyone runs and comes to him. Even on the sitra achara side one is elevated this way: when Hashem gave the Torah to Yisrael, all the umos came to Bilaam (Zevachim 116). Through matan Torah, Bilaam was elevated, the whole world came to him, and he stood himself on some pasuk and said to them Torah; they asked 'Hashem la-mabul yashav' (Psalms 29:10), and he stood on a pasuk and answered them 'Hashem oz' (29:11). And the same in Israel itself, with those in kedushah who do not, chas ve-shalom, come to a Bilaam-figure: when a great true tzaddik reveals chiddushim and a great commotion is made that he reveals such awesome chiddushim, then everyone gathers and comes to some lesser one and assembles to hear from him because of the rea'sh — the commotion — made through the chiddushim of the gadol; and he stands on some pasuk and says to them what he says.",
                "intermediate": "**K'she-tzaddik gadol amiti megaleh Torah — chiddushim nifla'im ve-nora'im — hu tovah la-ketanim be-ma'alah**, she-al-yedei zeh **nisgadel ha-katan be-ma'alah she-ha-kol ratzim u-va'im elav.** **Ve-gam ba-sitra-achara nisgadel echad al-yedei zeh** — ke-mo she-matzinu **be-Vilam**: k'she-natan Hashem yisborach et ha-Torah le-Yisrael, ba'u kol ha-umos le-Vilam (זבחים קטז.). Nimtza she-al-yedei netinas ha-Torah le-Yisrael nisgadel Bilam, u-va'u elav kol ha-olam, ve-hu amad atzmo al eizeh pasuk ve-amar la-hem Torah: she-alu **\"ה' לַמַּבּוּל יָשָׁב\"** (תה' כט:י), ve-hu amad al pasuk ve-heshiv la-hem **\"ה' עֹז\"** ve-chu' (כט:יא). **Ve-chen be-Yisrael atzman she-be-kedushah** ve-einan ba'im (chas ve-shalom) le-Vilam ve-cha-yotzei: k'she-tzaddik gadol amiti megaleh chiddushim ve-na'aseh **rea'sh gadol** she-ze megaleh chiddushim nora'im k'eilu — az **kulam miskab-tzim u-va'im le-eizeh katan be-ma'alah ve-ne'esafim etzlo lishmo'a mi-menu** — me-chamas ha-rea'sh ha-na'aseh al-yedei ha-chiddushim she-megaleh ha-tzaddik ha-gadol — ve-hu omed atzmo al eizeh pasuk ve-omer la-hem mah she-omer.",
                "scholarly": "[T2:57] רעש החידושים של הצדיק הגדול → גדלות גם לקטן (וגם בס\"א — בלעם). זבחים קטז.. \"ה' למבול ישב\" (תה' כט:י), \"ה' עוז\" (כט:יא)."
            }
        ]
    },
    58: {
        "title_en": "The Greater the Tzaddik, the More He Sees the World — Yesh vs. Ayin",
        "title_he": "יש בני אדם שאומרים",
        "segs": [
            {
                "beginner": "Some people say that when the tzaddik is great in stature, his very greatness keeps him from being able to gaze and look upon the people of the world — he is far from the world. In truth it is not so. On the contrary: when the tzaddik is very great, he can gaze and look upon the world more. Take Rabban Yochanan ben Zakkai, who was certainly far greater in stature than the tzaddikim of our time — and yet he said 'oy li im omar, oy li im lo omar' (Keilim 17:16) — meaning he was so familiar with the world that he was afraid to say words of Torah lest the deceivers learn from him. So familiar with the world that, on the contrary, he feared they would learn deceit from him! For in truth, the greater the tzaddik, the more he can gaze and look upon the world. For Hashem yisborach is exceedingly exalted from the world, and yet He gazes with hashgachah pratis upon all of it. The reason: one who is yesh cannot be in every place at once — when he stands here, he is not there; when he is occupied in some avodas Hashem, he cannot look upon the world. But one who is ayin — there is no place where he is not, for he has no place at all. Therefore the more the tzaddik is included in ayin, the more he can gaze upon the world. It is not appropriate to say of him that he is in a high and remote place from the world — for he has no place at all. (See Likutey Moharan I:162 in the name of the Maggid: 'one who wishes to be wise, let him go south.')",
                "intermediate": "**Yesh benei adam she-omrim, she-k'she-ha-tzaddik gadol be-ma'alah, me-chamas gadlaso eino yachol le-hashgi'ach ve-le-his-takel al benei ha-olam** — ki rachok me-ha-olam. **U-ve-emes eino ken** — ki **aderaba, k'she-ha-tzaddik gadol me'od, hu yachol le-hashgi'ach u-le-his-takel yoter al ha-olam.** Ke-mo she-matzinu **be-Rabban Yochanan ben Zakkai** — she-be-vadai hayah gadol be-ma'alah me'od me'od yoter ve-yoter mi-ha-tzaddikim she-bizman ha-zeh — ve-af-al-pi-chen amar **\"אוֹי לִי אִם אֹמַר, אוֹי לִי אִם לֹא אֹמַר\"** (כלים פי\"ז מט\"ז). Nimtza she-RYBZ hayah baki kol-kakh be-soch ha-olam ad she-hayah misya-rei lomar divrei Torah she-lo yilmedu mi-menu **ha-rama'im** — sof: aderaba hayah misya-rei pen yilmedu mi-menu rama'us! **Ki be-emes kol mah she-ha-tzaddik gadol be-yoter, yachol le-hashgi'ach u-le-his-takel ba-olam yoter** — ki Hashem yisborach hu meromam u-mnusa me'od me'od mi-ha-olam, ve-af-al-pi-chen mashgi'ach **be-hashgachah pratis al kol ha-olam.** Ki **mi she-hu yesh — eino yachol li-hyos be-chol makom be-vas achas**: kol mah she-yeshus — k'she-omed kan eino sham; kegon k'she-hu be-eizeh avodas Hashem eino yachol le-his-takel ba-olam. **Aval mi she-hu ayin — ein makom she-lo yiheyeh sham** — ki ein lo makom klal. **Ve-al-ken kol mah she-ha-tzaddik nichlal yoter ba-ayin, hu yachol le-hashgi'ach u-le-his-takel ba-olam be-yoter** — ki ein shayach lomar alav she-hu be-makom gavoh ve-rachok me-ha-olam, ki ein lo makom klal. (לק\"מ ח\"א קסב — ha-rotzeh le-hach-kim yad-rim).",
                "scholarly": "[T2:58] רחב\"ז: \"אוי לי אם אומר וכו'\" (כלים יז:טז). יש = מקום מוגבל; אין = בכל מקום. הצדיק הנכלל באין → השגחה פרטית. לק\"מ ח\"א קסב בשם המגיד: ה' למחכים — ידרים."
            }
        ]
    },
    59: {
        "title_en": "Zariz VeNiskar / VeNifsad — Bechinah Bein HaMitzvos",
        "title_he": "יש זריז ונשכר, זריז ונפסד",
        "segs": [
            {
                "beginner": "There is one who is zealous and gains, and one who is zealous and loses (Pesachim 50b). 'Mitzvah goreres mitzvah' (Avos 4) — one mitzvah drags another. There must be some bechinah between mitzvos that connects one mitzvah to its neighbor, by which they are dragged one after the other. And in truth this very bechinah — what is between the mitzvos — is itself extremely precious. Therefore one who is a tzaddik mi-ne'urav and walks the straight path from his days, going from level to level — like Avraham, 'and Avraham was old, ba ba-yamim' (Genesis 24:1), Avraham coming to his level through the days (Zohar Chayei Sarah 129a; ben shalosh shanim hikir es Bor'o, Nedarim 32a) — such a person, in this bechinah, loses through zealousness. When he is greatly zealous and runs ze-rizus from mitzvah to mitzvah, he forfeits the kedushah-bechinah between mitzvos: he passes over and skips it. The mitzvah itself is dragging him toward it through the previous mitzvah; if he too runs zealously into the mitzvah, he may skip and pass the in-between bechinah. He is zariz ve-nifsad. But when he tarries a little, he can in the meantime attain the bechinah bein ha-mitzvos. All this for one who walks be-darchei Hashem ke-seder mi-ne'urav. But a baal teshuvah must specifically be very, very zariz — to hasten and run, le-malet al nafsho — forbidden to tarry, to stand and settle. The baal teshuvah does not go from level to level at all; there is no bechinah-bein-ha-mitzvos between him and kedushah. He must begin anew, leap over what must be leapt over, and jump into kedushah be-zerizus gedolah. Such a person is zariz ve-niskar.",
                "intermediate": "**Yesh zariz ve-niskar, zariz ve-nifsad** (פסחים נ:). **\"מצוה גוררת מצוה\"** (אבות ד'). Ve-yesh **bechinah bein ha-mitzvos** — mah she-bein mitzvah le-mitzvah — she-mekasher mitzvah achas le-chavertah, asher al-yedei zeh ha-mitzvos nigrarim achas achar chavertah. U-ve-emes zos ha-bechinah atzmah **yekarah me'od.** Ve-al-ken: **mi she-tzaddik mi-ne'urav** ve-holech be-derech ha-yashar mi-yamav, **mi-darga le-darga** — \"וְאַבְרָהָם זָקֵן בָּא בַּיָּמִים\" (בר' כד:א), Avraham ba le-darga shelo al-yedei ha-yamim (זוה\"ק חיי\"ש קכט.; \"בן שלש שנים הכיר את בוראו\" נדרים לב.) — **ze, ba-bechinah zos, mafsid al-yedei zerizus**. Ki k'she-hu zariz gadol ve-rats bi-zerizus mi-mitzvah le-mitzvah, mafsid bechinas ha-kedushah she-bein mitzvah le-mitzvah, ki **al-yedei ha-zerizus over u-medaleg al ha-bechinah ha-zos** — ki ha-mitzvah atzmah holecheth elav (nigreres elav al-yedei ha-mitzvah ha-rishonah). U-ke-she-gam hu rats bi-zerizus el ha-mitzvah, az yuchal ledaleg u-la'avor et ha-bechinah ha-na\"l — ve-al-ken hu **zariz ve-nifsad**. Aval **k'she-shoheh ketzas — yuchal be-soch kakh le-hasig gam ha-bechinah she-bein ha-mitzvos.** Ve-chol zeh le-mi she-holech be-darchei Hashem ke-seder mi-ne'urav. **Aval mi she-tzarich la'asos teshuvah — tzarich dika li-hyos zariz gadol me'od me'od, le-maher ve-laruts me'od le-malet al nafsho** — ve-asur lo li-shhos klal la'amod u-le-his-yashev — ki **baal-teshuvah eino holech mi-darga le-darga klal** ve-ein beino u-vein ha-kedushah shum bechinah. Ki tzarich le-haschil **me-chadash**, ve-tzarich laruts u-ledaleg el ha-kedushah, ke-mu-vah she-ha-baal-teshuvah tzarich ledaleg al mah she-tzarich ledaleg, ve-likpotz el ha-kedushah bi-zerizus gedolah. **Ish ka-zeh hu zariz ve-niskar.**",
                "scholarly": "[T2:59a] זריז ונשכר/ונפסד (פסחים נ:). \"מצוה גוררת מצוה\" (אבות ד). \"ואברהם זקן בא בימים\" (בר' כד:א); זוה\"ק חיי\"ש קכט.; נדרים לב.. צדיק מנעוריו — שוהה בין מצוות; בעל תשובה — קופץ ומדלג."
            },
            {
                "beginner": "And the bechinah-bein-ha-mitzvos is, for example, 'va-yedaber Hashem el Moshe lemor — ve-asisa' (Exodus 25:1 and elsewhere). Surely there is avodah also in those words that come before the mitzvah itself. The essence of the mitzvah is stated in the Torah only afterward, after 'va-asisa.' But in truth there is avodah even in the verses that fall between mitzvah and mitzvah — and that is the bechinah being discussed: what stands between mitzvah and mitzvah. (See Likutey Moharan I:22 — there is avodah even in 'va-yedaber.')",
                "intermediate": "Ve-bechinah she-bein ha-mitzvos ha-na\"l hi ke-gon: **\"וַיְדַבֵּר ה' אֶל מֹשֶׁה לֵּאמֹר... וְעָשִׂיתָ\"** (שמ' כה:א ve-shar). U-ve-vadai **yesh avodah gam be-eilu ha-dibburim** she-hem kodem ha-mitzvah — ki ikar ha-mitzvah be-atzmah ne'emar ba-Torah achar-kakh, achar **תיבת \"ועשית\"**, **aval be-emes be-vadai gam ba-pesukim ha-na\"l she-bein mitzvah le-mitzvah yesh ba-hem avodah**, ve-zehu **bechinah ha-na\"l mah she-bein mitzvah le-mitzvah**. (לק\"מ ח\"א כב — yesh avodah gam be-pasuk \"וידבר\" וכו').",
                "scholarly": "[T2:59b] \"וידבר ה' אל משה... ועשית\" (שמ' כה:א ועוד) — אפילו בפתיחת המצוה יש עבודה. לק\"מ ח\"א כ\"ב."
            }
        ]
    },
    60: {
        "title_en": "Milchamos Causes Yakros; SD Comes from Eidim; Talmid She'eino Hagun → Atziras Geshamim",
        "title_he": "כשיש מלחמות בעולם, השכל מחייב שיהיה יקרות",
        "segs": [
            {
                "beginner": "When there are wars in the world, intellect requires there to be yakros (scarcity, high prices). For wars and bloodshed awaken the curse of Kayin: 'when you work the ground it shall not yield its strength to you' (Genesis 4:12) — through the bloodshed in the world. The curse was stated for shefichus damim, and the earth is liable in this when there is shefichus damim. Rains are made through the eidim — vapors — that rise from the earth: 've-ed ya'aleh min ha-aretz' (Genesis 2:6); from those eidim the rains are formed. When there are wars and shefichus damim, those very eidim become shefichus damim. As written: 'va-tagger es Bnei Yisrael al yedei cherev be-eis eidam' (Ezekiel 35:5–6) — bechinas the eidim through which shefichus damim is made. Likewise about Mitzrayim, Ammon, Moav: 'be-eis eidam' (Ezekiel 35:5 et al.). So when there is war, the earth gives its strength there — to bloodshed — for from her eidim is bloodshed made; therefore rain does not fall, since the eidim are diverted to another use. (Taanis 8b: 'in the time of rain even gisos cease' — when rains fall the gisos and wars cease.)",
                "intermediate": "**K'she-yesh milchamos ba-olam, ha-sechel mechayev she-yiheyeh yakros** — ki **nis-orer kilelas Kayin: \"כִּי תַעֲבֹד אֶת הָאֲדָמָה לֹא תֹסֵף תֵּת כֹּחָהּ לָךְ\"** (בר' ד:יב) — al-yedei shefichus damim. Ki kelelah zos ne'emrah al shefichus damim, ki ha-adamah chayeves bazos k'she-yesh shefichus damim. Ki **ha-geshamim na'asin al-yedei ha-eidim ha-olim min ha-aretz** — \"וְאֵד יַעֲלֶה מִן הָאָרֶץ\" (בר' ב:ו). U-min ha-eidim ha-olim min ha-aretz mizeh na'asim geshamim. Ve-k'she-yesh milchamos ve-shefichus damim, az **na'aseh me-ha-eidim ha-na\"l shefichus damim**: \"וַתַּגֵּר אֶת בְּנֵי יִשְׂרָאֵל עַל יְדֵי חֶרֶב בְּעֵת אֵידָם\" (יח' לה:ה-ו) — bechinas eidim ha-na\"l. Ve-chen be-kamah umos: Mitzrayim, Ammon, Mo'av — **\"בְּעֵת אֵידָם\"** (יח' לה:ה ve-shar) — bechinas eidim. Lachen k'she-yesh milchamos, ha-adamah nosenes kochah le-sham (la-shefichus damim), u-mi-menah ein yordim geshamim — ki ha-geshamim na'asim me-ha-eidim, ve-achshav na'aseh me-ha-eidim inyan acher: shefichus damim. (תענית ח: 'בשעת גשמים אפילו גיסות פוסקות בו') — k'she-yesh geshamim, nifsakim ha-gisos ve-ha-milchamos.",
                "scholarly": "[T2:60a] מלחמות → יקרות. קללת קין: \"לא תוסיף תת כוחה\" (בר' ד:יב); \"ואד יעלה\" (בר' ב:ו). \"בעת אידם\" (יח' לה:ה-ו). תענית ח: \"בשעת גשמים אפילו גיסות פוסקות\"."
            },
            {
                "beginner": "Connected to this is the gemara (Pesachim 112a): when R. Akiva was in tefisah, R. Shimon ben Yochai said to him, 'Rabbi, teach me Torah, and if not — I will tell Yochai my father, and he will hand you over la-malchus.' These are extremely astonishing words — that R. Shimon would speak this way to his rebbe, threatening to hand him over to the malchus. And presumably, when his rebbe R. Akiva did not want to teach him, he certainly intended for the good. And besides — was R. Akiva not already imprisoned? What further handing-over could there be?",
                "intermediate": "**U-le-zeh mekasher mah she-amru chaza\"l: \"כשהיה רבי עקיבא בתפיסה אמר לו ר' שמעון בן יוחאי: רבי, למדני תורה, ואם לאו, אני אומר ליוחאי אבא ומוסרך למלכות\"** (פסחים קיב.). **U-ve-vadai ha-devarim temuhim me'od me'od** she-RaShBY yomar ka-devarim ha-eilu le-rabo she-yim-serehu la-malchus. Ve-gam ki **mi-stama k'she-Rabi Akiva rabo lo ratzah le-lamdo, be-vadai kavan le-tovah**. Ve-gam ha-lo kvar hayah tafus ba-tefisah, u-mah yim-serehu od?",
                "scholarly": "[T2:60b] פסחים קיב.: ר\"ש בן יוחאי לר\"ע — \"למדני תורה ואם לאו אני אומר ליוחאי אבא ומוסרך למלכות\". קושיות: לרבו? וכי לא היה כבר תפוס?"
            },
            {
                "beginner": "But know: through one who says Torah be-rabim and listeners who are not hagun (worthy) hear, atziras geshamim also comes. For through kavod ha-Torah rains come — bechinas 've-chvod Hashem nir'ah ba-anan' (Exodus 16:10) — and through the anan come geshamim. Bechinas 'Kel ha-kavod hir'im, Hashem al mayim rabim' (Psalms 29:3) — geshamim that come through kavod Hashem, kavod ha-Torah. One who teaches Torah to a talmid she-eino hagun — chaza\"l said (Chullin 133a) it is as if he throws a stone to Markulis. And Tosfos (Sanhedrin 64a, s.v. Markulis) explained Markulis = mar killus, master of disgrace — heipech ha-kavod. So when one teaches Torah to a talmid she-eino hagun, it is heipech ha-kavod, and through this comes atziras geshamim — heipech ha-kavod that brings rains. As Mishlei 26:1: 'ka-matar ba-katzir, ken lo na'aveh li-chsil kavod' — when one teaches Torah to a talmid she-eino hagun (= 'noten li-chsil kavod' — Chullin shem), one ruins the rains. 'Ka-matar ba-katzir' = ruined rains, falling out of season — at the harvest, rain harms; just so 'lo na'aveh li-chsil kavod,' for through that itself one ruins the rains.",
                "intermediate": "**Ach da, ki gam al-yedei mi she-omer Torah be-rabim ve-shomim talmidim she-einan hagunim — al-yedei zeh ba gam-ken atziras geshamim.** Ki **al-yedei kvod ha-Torah ba geshamim** — bechinas \"וּכְבוֹד ה' נִרְאָה בֶּעָנָן\" (שמ' טז:י), ve-al-yedei ha-anan ba geshamim. Bechinas **\"אֵל הַכָּבוֹד הִרְעִים, ה' עַל מַיִם רַבִּים\"** (תה' כט:ג) — geshamim ha-ba'im al-yedei kvod Hashem, bechinas kvod ha-Torah. Ve-ha-lomed Torah le-talmid she-eino hagun amru chaza\"l (חולין קלג.) **\"כזורק אבן למרקוליס\"**. U-fershu chaza\"l (תוס' סנה' סד. ד\"ה מרקולי\"ס): **מ\"ר קלו\"ס** — heipech ha-kavod. Nimtza k'she-lomed Torah le-talmid she-eino hagun — heipech ha-kavod, ve-al-ken al-yedei zeh ba atziras geshamim — heipech ha-kavod she-al-yado ba'im geshamim. Ve-zehu bechinas **\"כְּמַטָּר בַּקָּצִיר כֵּן לֹא נָאוֶה לִכְסִיל כָּבוֹד\"** (משלי כו:א) — k'she-lomed Torah le-talmid she-eino hagun — bechinas \"נותן לכסיל כבוד\" — al-yedei zeh **mekalkel ha-geshamim**: \"ka-matar ba-katzir\" — ki-lekul ha-geshamim she-yordim she-lo bi-itan; **bi-she'as ha-katzir aderaba mazik ha-matar** — ken lo na'aveh li-chsil kavod, ki al-yedei zeh be-atzmo hu kilekul ha-geshamim.",
                "scholarly": "[T2:60c] תורה ברבים לתלמיד שאינו הגון → היפך הכבוד → עצירת גשמים. \"וכבוד ה' נראה בענן\" (שמ' טז:י). \"אל הכבוד הרעים\" (תה' כט:ג). \"כזורק אבן למרקוליס\" (חולין קלג.); תוס' סנה' סד. — מר קלוס. \"כמטר בקציר... לא נאוה לכסיל כבוד\" (משלי כו:א)."
            },
            {
                "beginner": "And this is what RaShBY said to R. Akiva — 'lamdeini Torah, ve-im lav, ani omer.' R. Akiva would gather kehilos and expound be-rabim, and RaShBY held that this was why he was caught in tefisah — because he expounded be-rabim and people who were not hagun heard. For through chiddushei Torah revealed, Elokus is drawn ki-vyachol: 'va-yikchu li terumah' (Exodus 25:2) — when you wish to take and draw Me, only through Torah; through the Torah He is drawn ki-vyachol. To where is the Elokus drawn? Into the moach of the listener. And although that is itself a kind of tefisah ki-vyachol — bechinas 'melech asur ba-rehatim' = berahatei mochin (Tikkunei Zohar end, Tikkun 6, 5a; see Tikkun 6, 21b), 'asur' precisely — that His Elokus yisborach is drawn berahatei mochin is bechinas tefisah, bechinas 'shavisa shevi' (Psalms 68:19) — nevertheless it is nicha to Hashem yisborach that He be drawn through the Torah, even though it is bechinas tefisah. But when one teaches Torah to a talmid she-eino hagun and draws His Elokus into that mind — zeh tefisah mamash, and therefore his onesh is tefisah. RaShBY thought that this is why R. Akiva was caught in tefisah; through the tefisah, the words he had introduced to talmidim she-einan hagunim would be rectified and refined — bechinas 've-atem he-as-ru ve-yibachanu divreichem' (Genesis 42:16). Therefore RaShBY said, 'lamdeini Torah,' so that by teaching him now, the previous flaw — that he had taught Torah to talmidim she-einan me-hugnam — would be repaired.",
                "intermediate": "**Ve-zehu she-amar RaShBY le-Rabi Akiva: \"לַמְּדֵנִי תּוֹרָה, וְאִם לָאו, אֲנִי אוֹמֵר\"** וכו'. Ki Rabi Akiva hayah **makhil kehilos ve-doresh be-rabim**, ve-savar RaShBY she-mi-pnei zeh nispas ba-tefisah — me-chamas she-haya doresh be-rabim ve-shamu benei adam she-einam me-hugnam. Ki **al-yedei chiddushei Torah she-megalin nimshach Elokus ki-vyachol** — **\"וְיִקְחוּ לִי תְּרוּמָה\"** (שמ' כה:ב): k'she-tirzu likach u-le-hamshich osi, ee-efshar ki im al-yedei ha-Torah. U-le-heichan nimshach ha-Elokus? **Le-soch moach ha-shomea**. Ve-af she-zehu **tefisah ki-vyachol** — bechinas **\"מֶלֶךְ אָסוּר בָּרְהָטִים\"** (שיה\"ש ז:ו) — **be-rahatei mochin** (סוף תיקוני זוה\"ק תיקון ו' ה.; ת\"ו כא:) — 'asur' dika, she-mah she-nim-shach Elokuso ki-vyachol berahatei mochin hu **bechinas tefisah**, bechinas **\"שָׁבִיתָ שֶּׁבִי\"** (תה' סח:יט) — af-al-pi-chen nicha la-Hashem yisborach she-yiheyeh nimshach al-yedei ha-Torah, af she-hu bechinas tefisah. **Aval k'she-lomed Torah le-talmid she-eino hagun u-mamshich Elokuso le-soch mocho — zos tefisah mamash, ve-al-ken oneshs tefisah.** Ve-al-ken savar RaShBY she-al-yedei zeh nispas Rabi Akiva ba-tefisah — ki **al-yedei ha-tefisah yis-takein ve-yiz-dakekhu ha-dibburim she-hichnis le-talmidim she-einan hagunim** — bechinas **\"וְאַתֶּם הֵאָסְרוּ וְיִבָּחֲנוּ דִּבְרֵיכֶם\"** (בר' מב:טז). Ve-al-ken amar RaShBY le-Rabi Akiva she-yi-lemdenu Torah, ve-al-yedei she-yi-lemad atah le-RaShBY — al-yedei zeh yi-takein ha-pgam ha-na\"l, **she-lamad Torah le-talmidim she-einan me-hugnam**.",
                "scholarly": "[T2:60d] \"ויקחו לי תרומה\" (שמ' כה:ב). \"מלך אסור ברהטים\" (שיה\"ש ז:ו) — תיק\"ז ת\"ו ה. ו-כא:. \"שבית שבי\" (תה' סח:יט). תפיסה לתיקון הדיבורים: \"ואתם האסרו ויבחנו דבריכם\" (בר' מב:טז). למידת תורה לתלמיד שאינו הגון = תפיסה ממש."
            },
            {
                "beginner": "'And if not — ani omer le-Yochai abba' — 'I will say' precisely: I will say Torah myself, in the bechinah of 'Yochai my father' — bechinas chasadim mi-tzad ha-av, the source of Torah-revelation, since giluy ha-Torah is giluy ha-chasadim (Kesuvos 96a: 'kol ha-monea talmido mi-le-shamsho — ke-ilu monea mimenu chesed' — Job 6:14). Each person has chasadim and gevuros: chasadim mi-tzad ha-av, etc. R. Akiva had no chasadim mi-tzad ha-av — he was ben gerim, lacking zechus avos (Berachos 27b: they did not appoint him nasi mi-shum de-leis lei zechus avos). RaShBY thought R. Akiva did not want to say Torah for this reason. But RaShBY had chasadim mi-tzad aviv R. Yochai (a great one in Israel — Hakdamas Zohar 11a, 'Yochai ha-bar-na'). Therefore RaShBY said: 've-im lav — ani omer le-Yochai abba' — I will say Torah, bechinas chasadim mi-tzad ha-av, source of giluy ha-Torah, giluy ha-chasadim. And 'u-mosrekha la-malchus' — Rabbi Shimon thought that R. Akiva's reluctance to say Torah and reveal the chasadim came only from his anvanus: in his humility R. Akiva thought he could not reveal Torah without chasadim mi-tzad ha-av and could only repair the pegam through tefisah (since tefisah is tikkun and zikkukh la-dibburim). But really R. Akiva is so great he has chasadim mi-tzad atzmo and does not need zechus avos at all — he can reveal Torah through chasadim mi-tzad atzmo and rectify the pegam thus. (The Rebbe did not explain how giluy ha-Torah revealing chasadim rectifies that flaw, nor how a talmid with zechus avos saying Torah forces his rebbe into gadlus and into saying Torah.)",
                "intermediate": "**\"וְאִם לָאו, אֲנִי אוֹמֵר\" — 'אני אומר' דייקא** — RaShBY amar le-Rabi Akiva: im einecha rotzeh lelamdeni, **ani omer Torah**. Ve-zehu **\"אני אומר ליוחאי אבא\"** — ki **kol chiddushei Torah she-megalin — al-yedei zeh megalin chasadim** (כתוב' צו: 'כל המונע תלמידו מלשמשו, כאילו מונע ממנו חסד' — איוב ו:יד). Ve-yesh be-chol echad chasadim ve-gevuros — **chasadim mi-tzad ha-av** etc. **R. Akiva lo hayah lo chasadim mi-tzad ha-av** — ki **ben gerim** hayah, ve-lo hayah lo **zechus avos** (ברכות כז: she-lo banu le-manoso nasi 'di-leis leih zechus avos'). Ve-savar RaShBY she-Rabi Akiva eino rotzeh lomar Torah me-chamas zeh — she-ein lo chasadim mi-tzad ha-av. **Aval RaShBY hayah lo chasadim mi-tzad aviv R. Yochai** (gadol be-Yisrael — הקדמת זוה\"ק יא. \"יוחאי הברנא\"). Ve-al-ken amar RaShBY: 've-im lav — ani omer le-Yochai abba' — **she-ani omer Torah she-hi bechinas \"Yochai abba\" — bechinas chasadim mi-tzad ha-av** she-misham hisgalus ha-Torah, ki hisgalus ha-Torah = hisgalus ha-chasadim. **Ve-zehu \"ומוסרך למלכות\"** — RaShBY savar she-zos she-Rabi Akiva eino rotzeh lomar Torah u-le-galos ha-chasadim, **rak me-chamas anvanuso** shel R. Akiva (anav hu, sover she-eino yachol legalos Torah me-chamas she-ein lo chasadim mi-tzad ha-av; eino yachol le-takkein ha-pgam ela al-yedei tefisah — she-ha-tefisah tikun ve-zikkukh la-dibburim). **Aval be-emes Rabi Akiva rabbi gadol ka-zeh she-yesh lo chasadim mi-tzad atzmo, ve-eino tzarich le-zechus avos klal**, ve-yachol R. Akiva legalos Torah al-yedei ha-chasadim she-yesh lo mi-tzad atzmo levad — ve-al-yedei zeh yi-takein ha-pgam. (**Ve-lo bei'er** eich al-yedei hisgalus ha-Torah ha-megalin chasadim al-yedei zeh yi-takein ha-pgam; ve-gam lo bei'er eich al-yedei ha-talmid she-yesh lo zechus avos k'she-megaleh Torah — al-yedei zeh yih-yeh rabo mukhrach lavo bi-gdulah ve-lomar Torah).",
                "scholarly": "[T2:60e] גילוי תורה = גילוי חסדים. כתובות צו.: \"כל המונע תלמידו מלשמשו כאילו מונע חסד\"; איוב ו:יד. ר\"ע בן גרים — ברכות כז:; אין זכות אבות. רשב\"י — \"יוחאי הברנא\"; הקדמת זוה\"ק יא.. סברת רשב\"י: ר\"ע ענו, וצריך להביאו בעל-כרחו לגדלות. (הערה: הרבי לא ביאר המנגנון המלא)."
            },
            {
                "beginner": "And this is 'u-mosrekha la-malchus' — 'mesirah' is a lashon of be-al-korcho ('va-yim-saru me-alfei Yisrael' — Numbers 31:5; Rashi: she-nim-seru be-al-korcham). RaShBY will bring R. Akiva be-al-korcho into the bechinah of gadlus through his own (RaShBY's) saying Torah — and R. Akiva will be compelled to come into gadlus and say Torah, which is hisgalus ha-chasadim, the tikkun of the pegam. By RaShBY the talmid revealing Torah from chasadim mi-tzad ha-av, R. Akiva will be brought to the bechinah of gadlus be-al-korcho until he is compelled to say Torah himself.",
                "intermediate": "**Ve-zehu \"ומוסרך למלכות\"** — **mesirah lashon be-al-korcho**, ke-mo she-katuv **\"וַיִּמָּסְרוּ מֵאַלְפֵי יִשְׂרָאֵל\"** (במ' לא:ה) — peresh Rashi: 'she-nim-seru be-al-korcham'. Ki **RaShBY yavi et Rabi Akiva be-al-korcho li-vchinas gadlus al-yedei she-hu yomar Torah** — ad she-yikrach R. Akiva be-al-korcho lavo bi-gdulah ve-lomar Torah — she-hi **hisgalus ha-chasadim** — tikkun ha-pgam ha-na\"l.",
                "scholarly": "[T2:60f] מסירה = בעל-כרחו. \"וימסרו מאלפי ישראל\" (במ' לא:ה); רש\"י שם. תלמיד עם זכות אבות מגלה תורה → רבו מוכרח לגדלות → גילוי חסדים → תיקון פגם הלימוד לתלמידים שאינם מהוגנים."
            }
        ]
    }
}

count_segs = 0
for n, info in torahs.items():
    src_path = os.path.join(src_dir, f"torah-{n}.json")
    with open(src_path, 'r', encoding='utf-8') as f:
        src = json.load(f)
    src_count = len(src['segments'])
    my_count = len(info['segs'])
    assert src_count == my_count, f"T{n}: src has {src_count} segs, PNC has {my_count}"
    segs_out = []
    for s in info['segs']:
        segs_out.append({
            "beginner": {"en": s["beginner"], "he": ""},
            "intermediate": {"en": s["intermediate"], "he": ""},
            "scholarly": {"en": "", "he": s["scholarly"]}
        })
    data = {
        "id": f"pnc-2-{n}",
        "book": "pettek-nanach-commentary",
        "part": 2,
        "torah": n,
        "title": f"T{n} (Tinyana) PNC - {info['title_en']}",
        "hebrewTitle": info['title_he'],
        "author": "Pettek Nanach",
        "segments": segs_out
    }
    out_path = os.path.join(pnc_dir, f"tinyana-{n}.json")
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(out_path, 'r', encoding='utf-8') as f:
        rt = json.load(f)
    assert rt['id'] == data['id']
    assert len(rt['segments']) == src_count
    count_segs += my_count
    print(f"T{n}: OK ({my_count} segs)".encode('ascii', 'replace').decode())

with open(commentaries_path, 'r', encoding='utf-8') as f:
    cdata = json.load(f)

if '2' not in cdata:
    cdata['2'] = {}

for n, info in torahs.items():
    sn = str(n)
    if sn not in cdata['2']:
        cdata['2'][sn] = {}
    cdata['2'][sn]['running_commentary'] = {
        "book": "pettek-nanach-commentary",
        "slug": "pettek-nanach-commentary",
        "status": "available",
        "url": f"/reader/pettek-nanach-commentary/tinyana-{n}.json",
        "layers": ["beginner", "intermediate", "scholarly"],
        "author": "Pettek Nanach",
        "label": f"Pettek Nanach Running Commentary - Tinyana T{n} ({info['title_en']})"
    }

with open(commentaries_path, 'w', encoding='utf-8') as f:
    json.dump(cdata, f, ensure_ascii=False, indent=2)

print(f"Total segs: {count_segs} across {len(torahs)} torahs".encode('ascii', 'replace').decode())
print("Registered in lm-commentaries.json".encode('ascii', 'replace').decode())
