#!/usr/bin/env python3
"""Portable deterministic generator; authenticates frozen authority before writes.

No corpus re-authoring, git dependency, host path, normalization or new revision.
Run with --app and --site pointing to the two candidate worktrees. Template and
this generator are identical in both trees. The prior evidence generator stays
immutable. The three full-book hashes are derived from independently reviewed
original/qatan/final objects; corpus hashes also agree with the pinned ledger.
"""
import argparse
import copy
import hashlib
import json
from pathlib import Path

LEDGER = '8c493378092dabc9cce9777811a762364cc6bfe573297dba33bc178ded2f37a1'
HASHES = {
    'before': '689ac867832c91e2e65c45d3e8f9ff1c5cf81a310f00c20d060e66a4f3622aaf',
    'qatan': '1a12f6c64cacbfefb8f99669398356af786a55c672962f1afc4c832d99487ae4',
    'final': '4ed18b3932e48e46880c6b6172b5878626557d612fde957bb9637e958d4aa337',
}
def digest(obj):
    return hashlib.sha256(json.dumps(obj, ensure_ascii=False, sort_keys=True,
                                     separators=(',', ':')).encode('utf-8')).hexdigest()

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--app', type=Path, required=True)
    p.add_argument('--site', type=Path, required=True)
    p.add_argument('--check', action='store_true', help='verify deterministic outputs without writes')
    args = p.parse_args()
    ledger = json.loads((args.app / 'scripts/data/psalms-annotation-ledger.json').read_bytes())
    if digest(ledger) != LEDGER:
        raise ValueError('frozen combined ledger mismatch')
    if (args.site / 'scripts/data/psalms-annotation-ledger.json').read_bytes() != (args.app / 'scripts/data/psalms-annotation-ledger.json').read_bytes():
        raise ValueError('app/site ledger bytes differ')
    qatan = json.loads((args.app / 'scripts/data/psalms-qatan-ledger.json').read_bytes())
    if digest(qatan) != ledger['qatan_ledger_sha256']:
        raise ValueError('frozen qatan ledger mismatch')
    book = json.loads((args.site / 'public/reader/medooyuk/tanach-tehillim.json').read_bytes())
    if digest(book) != HASHES['final']:
        raise ValueError('reviewed final whole book mismatch')
    for state, expected in HASHES.items():
        obj = copy.deepcopy(book)
        for entry in ledger['entries']:
            obj['ch'][str(entry['chapter'])][str(entry['verse'])]['m'] = copy.deepcopy(entry['states'][state]['m'])
        if digest(obj['ch']) != ledger['corpus_sha256'][state] or digest(obj) != expected:
            raise ValueError('reviewed whole book state mismatch: ' + state)
    template = (Path(__file__).parent / 'psalms-cache-contract.js').read_text()
    for name in ('prepare-psalms-cache-integrity.py', 'psalms-cache-contract.js'):
        if (args.app / 'scripts' / name).read_bytes() != (args.site / 'scripts' / name).read_bytes():
            raise ValueError('app/site generator source differs: ' + name)
    if template.count('__REVIEWED_HASHES__') != 1:
        raise ValueError('template marker mismatch')
    body = '// Generated by scripts/prepare-psalms-cache-integrity.py; do not edit.\n' + template.replace('__REVIEWED_HASHES__', json.dumps(HASHES, separators=(',', ':')))
    ts = body.replace('function canonical(value)', 'function canonical(value: any): string').replace('function sha256(text)', 'function sha256(text: string): string').replace('function rotate(x, n)', 'function rotate(x: number, n: number): number').replace('function valid(data, current)', 'function valid(data: any, current: boolean): boolean')
    ts += '\nexport const PSALMS_TEXT_REVISION = revision;\nexport const validPsalmsBook = valid;\n'
    js = "/* Psalms-only authenticated contract shared by page and worker. */\n(function(root) {\n'use strict';\n" + body + '''
var url = '/reader/medooyuk/tanach-tehillim.json?v=' + revision;
var pending = null;
function load() {
  if (pending) return pending;
  pending = fetch(url, {cache:'no-cache'}).then(function(r) {
    if (!r.ok) throw Error('Psalms HTTP ' + r.status);
    return r.json();
  }).then(function(data) {
    // An old worker may return an exact reviewed legacy state even online.
    // Accept only the three authenticated objects; never relabel legacy current.
    if (!valid(data, false)) throw Error('Invalid Psalms book');
    return data;
  }).catch(async function(error) {
    if (typeof caches !== 'undefined') {
      var keys = [url, '/reader/medooyuk/tanach-tehillim.json',
        '/reader/medooyuk/tanach-tehillim.json?v=uxlc25-gold-qk-ketiv-20260928-v2'];
      for (var key of keys) {
        try {
          var saved = await caches.match(key);
          if (saved) { var data = await saved.json(); if (valid(data, key === url)) return data; }
        } catch (_) {}
      }
    }
    throw error;
  });
  var result = pending;
  result.then(function(){pending=null;},function(){pending=null;});
  return result;
}
root.AjewPsalmsData = {revision:revision, url:url, valid:valid, load:load};
})(typeof self !== 'undefined' ? self : window);
'''
    outputs = {args.app / 'services/psalmsAnnotationRevision.ts': ts,
               args.site / 'public/psalms-data.js': js}
    for path, content in outputs.items():
        if args.check:
            if path.read_bytes() != content.encode():
                raise ValueError('non-deterministic generated output: ' + str(path))
        else:
            path.write_text(content)
    print(json.dumps({'states': HASHES, 'outputs': {str(p): hashlib.sha256(v.encode()).hexdigest() for p, v in outputs.items()}, 'check': args.check}, indent=2))

if __name__ == '__main__':
    main()
