#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 34 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/34'; SHA='f831b7a589474499ea1e6b7241ee0a5ed1b910148324449210209760a48792b7'; COUNTS=[2,2,3,6,2,3,7,6,9]; AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
EXPECTED={1:[1],2:[2],3:[3,4],4:[5,6,7],5:[8,9,10,11,12,13],6:[14,15],7:[16,17,18],8:[19,20,21,22,23,24,25],9:[26,27],10:[28,29,30,31],11:[32,33,34,35,36,37,38,39,40]}
def load(p): return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',v or '')).strip()
def req(c,m):
 if not c: raise RuntimeError(m)
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--pending-facsimiles',action='store_true'); a=ap.parse_args(); study=load(BASE/'torah-study.json'); s=study['segments']; refs=[f'Likutei Moharan 34:{section}:{leaf}' for section,n in enumerate(COUNTS,1) for leaf in range(1,n+1)]
 req(len(s)==40 and [z['index'] for z in s]==list(range(1,41)) and [z['sourceRef'] for z in s]==refs,'40 exact records/refs'); req(all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in s),'bilingual witness'); req(study['productionAlignedPassages']==study['productionDisplayRecords']==study['sefariaPassages']==40 and study['sefariaSectionCounts']==COUNTS and study['restoredBilingualSupplements']==study['structuralRestorations']==0,'counts')
 src=study['source']; req(src['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and src['license']=='CC-BY-NC' and src['versionSource']=='https://www.nli.org.il/he/books/NNL01','English license'); req(src['heVersionTitle']=='Likutei Moharan - rabenubook.com' and src['heLicense']=='Public Domain' and src['prev']=='Likutei Moharan 33:9' and src['lastNext']=='Likutei Moharan 35:1','Hebrew license/bounds'); req('וְאַתֶּם תִּהְיוּ לִי מַמְלֶכֶת כֹּהֲנִים' in plain(s[0]['he_nikud']) and 'V’atem Tihiyu Li Mamlekhet Kohanim' in plain(s[0]['en']) and 'וּכְשֶׁמְּדַבֵּר עִם חֲבֵרוֹ בְּיִרְאַת שָׁמַיִם' in plain(s[-1]['he_nikud']),'anchors')
 by={i:[z['index'] for z in s if int(z['classicSegment'])==i] for i in range(1,12)}; req(by==EXPECTED,'classic crosswalk')
 ph=load(BASE/'phrase-study.json'); req(len(ph['phrases'])==30 and ph['representedSections']==list(range(1,10)) and len(ph['selectedPassages'])==9,'30 phrases/all sections')
 for x in ph['phrases']:
  z=s[x['segment']-1]; req(x['source']==x['sourceRef']==z['sourceRef'] and x['he'] in plain(z['he']) and x['enMatch'] in plain(z['en']),'phrase provenance/text'); req(all(f'data-inline-phrase="{x["id"]}"' in z[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-34.json'); req(len(p['segments'])==11 and p['layerAvailability']==AV and [z['alignedPassages'] for z in p['segments']]==[EXPECTED[i] for i in range(1,12)],'Pettek crosswalk'); req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek truth')
 biur=load(BASE/'biur-halikutim.json'); req(biur['segments']==[] and biur['totalSegments']==0 and biur['availability']=='unavailable','Biur unavailable'); par=load(BASE/'parparos-lechochma.json'); req(len(par['segments'])==7 and par['sourceIndices']==[2,3,5,7,9,11,13] and par['availability']=='hebrew-only' and all(z['he'] and not z.get('en') for z in par['segments']),'Parparos 7 HE-only')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-34.json'); ids=[f'p34{chr(97+i)}' for i in range(6)]; req(len(prayer['segments'])==6 and prayer['assignedPackageIds']==ids and [z['sourceContainerOrdinal'] for z in prayer['segments']]==list(range(8,14)) and prayer['navigation']['prevUrl'] and prayer['navigation']['nextUrl'] and prayer['excludedMetadata']['dateBarText']==['26 Kislev','27 Kislev','28 Kislev'],'prayer schema'); req(prayer['segments'][0]['he'].startswith('פִּי יְדַבֵּר חָכְמוֹת') and prayer['segments'][0]['en'].startswith('My mouth shall speak wisdom') and prayer['segments'][-1]['he'].startswith('וּתְזַכֵּנִי לְקַדֵּשׁ אֶת פִּי') and prayer['segments'][-1]['en'].startswith('And grant me merit to sanctify my mouth') and all('עברית ▾' not in z['en'] for z in prayer['segments']),'prayer content')
 nn=load(BASE/'likutay-nanach.json'); indices=list(range(102,129)); req(len(nn['segments'])==27 and [z['sourceIndex'] for z in nn['segments']]==indices and all(z['he'] and not z.get('en') for z in nn['segments']) and [x['index'] for x in nn['excludedHeadings']]==[101,129],'Nanach bounds'); rel=load(ROOT/'src/data/lm-commentaries.json')['1']['34']['related_commentaries']; nr=[z for z in rel if z.get('book')=='likutay-nanach']; pr=[z for z in rel if z.get('book')=='parparos-lechochma']; req(len(nr)==len(pr)==1 and nr[0]['totalRecords']==27 and pr[0]['totalRecords']==7,'registry')
 m=load(BASE/'peer-halikutim/manifest.json'); req(m['sourceSha256']==SHA and m['hebrewBooksId']==66040 and m['sourcePageRange']==[441,499] and [z['sourcePage'] for z in m['pages']]==list(range(441,500)),'Pe’er range'); assets={x.name for x in (BASE/'peer-halikutim').glob('page-*.webp')}; expected={f'page-{x}.webp' for x in range(441,500)}; pdf=(BASE/'peer-halikutim/peer-halikutim-torah-34.pdf').is_file(); req(not (BASE/'peer-halikutim/page-440.webp').exists() and not (BASE/'peer-halikutim/page-500.webp').exists(),'excluded assets')
 if a.pending_facsimiles: req(not assets and not pdf and m['facsimileStatus'].startswith('pending'),'pending facsimiles')
 else: req(assets==expected and pdf and m['facsimileStatus']=='ready','facsimiles ready')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/34.astro').read_text(); req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers'); req('exactly 40 bilingual leaves across sections 34:1–9' in astro and 'pages 441–499' in astro and 'Biur is unavailable' in astro and '27 substantive Hebrew-only' in astro and '6 authoritative paired bilingual blocks' in astro and 'https://www.peer-halikutim.com/' in astro,'route truth/credit')
 classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(); directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(); req(classic.count('29, 30, 31, 32, 33, 34]')>=2 and 'length: 34' in directory and '<= 34' in directory and "'כט','ל','לא','לב','לג','לד'" in directory,'discovery')
 print('Validated Torah 34: 40 exact bilingual leaves across 9 sections, 30 phrases, 9 layers, Pettek 11 asymmetric, Biur unavailable, Parparos 7 HE-only, Nanach 27 HE-only, prayer 6 bilingual, Pe’er 441–499; '+('facsimiles pending separately supervised conversion.' if a.pending_facsimiles else 'facsimiles ready.'))
if __name__=='__main__': main()
