#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 29 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/29'; SHA='f831b7a589474499ea1e6b7241ee0a5ed1b910148324449210209760a48792b7'; COUNTS=[5,3,11,9,8,5,3,2,8,1,14,6]
AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
EXPECTED={1:[1],2:[2],3:[3],4:list(range(4,7)),5:list(range(7,10)),6:list(range(10,21)),7:list(range(21,30)),8:list(range(30,33)),9:list(range(33,38)),10:list(range(38,43)),11:list(range(43,46)),12:list(range(46,48)),13:list(range(48,56)),14:[56],15:list(range(57,71)),16:list(range(71,77))}
def load(p): return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',v or '')).strip()
def req(c,m):
 if not c: raise RuntimeError(m)
def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--pending-facsimiles',action='store_true'); args=parser.parse_args(); study=load(BASE/'torah-study.json'); segs=study['segments']; refs=[f'Likutei Moharan 29:{s}:{l}' for s,n in enumerate(COUNTS,1) for l in range(1,n+1)]
 req(len(segs)==76 and [z['index'] for z in segs]==list(range(1,77)),'76 display records'); req([z['sourceRef'] for z in segs if isinstance(z.get('sourceComment'),int)]==refs,'exact Sefaria refs'); req(all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in segs),'bilingual witness invariant'); req(study['productionAlignedPassages']==76 and study['productionDisplayRecords']==76 and study['sefariaPassages']==75 and study['sefariaSectionCounts']==COUNTS and study['restoredBilingualSupplements']==1 and study['structuralRestorations']==0,'counts')
 source=study['source']; req(source['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and source['license']=='CC-BY-NC' and source['versionSource']=='https://www.nli.org.il/he/books/NNL01','English license'); req(source['heVersionTitle']=='Likutei Moharan - rabenubook.com' and source['heLicense']=='Public Domain' and source['prev']=='Likutei Moharan 28:6' and source['lastNext']=='Likutei Moharan 30:1','Hebrew license/boundaries'); req(segs[0]['sourceRef']=='Likutei Moharan 29:1:1' and segs[-1]['sourceRef']=='Likutei Moharan 29:12:6' and 'האי גברא דאזל בעי אתתא' in plain(segs[0]['he']),'anchors'); req(segs[1]['sourceRef']=='Classic Torah 29 physical segment 2' and segs[1]['supplementType']=='exact-bilingual-classic-rashi' and plain(segs[1]['he']).startswith('רש"י: דמדליה מנה') and plain(segs[1]['en']).startswith('Rashi: To a place higher than her'),'Classic supplement')
 by={i:[z['index'] for z in segs if int(z['classicSegment'])==i] for i in range(1,17)}; req(by==EXPECTED,'classic crosswalk')
 phrases=load(BASE/'phrase-study.json'); req(len(phrases['phrases'])==30 and phrases['representedSections']==list(range(1,13)),'30 phrases/12 sections'); req(len(phrases['selectedPassages'])==12 and len(set(phrases['selectedPassages']))==12,'selected passages')
 for phrase in phrases['phrases']:
  seg=segs[int(phrase['segment'])-1]; req(phrase['source']==phrase['sourceRef']==seg['sourceRef'],'phrase provenance'); req(phrase['he'] in plain(seg['he']) and phrase['enMatch'] in plain(seg['en']),'exact phrase text'); req(all(f'data-inline-phrase="{phrase["id"]}"' in seg[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-29.json'); req(len(p['segments'])==16 and p['layerAvailability']==AV,'Pettek count/availability'); req([z['alignedPassages'] for z in p['segments']]==[EXPECTED[i] for i in range(1,17)],'Pettek crosswalk'); req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek language truth')
 biur=load(BASE/'biur-halikutim.json'); req(len(biur['segments'])==3 and [z['sourceIndex'] for z in biur['segments']]==[1,2,3] and all(z['he'] and not z.get('en') for z in biur['segments']) and biur['availability']=='hebrew-only','Biur 3 HE-only'); par=load(BASE/'parparos-lechochma.json'); pi=[2,3,5,7,9,11,13,15,17,19,21,23,25]; req(len(par['segments'])==13 and par['sourceIndices']==pi and all(z['he'] and not z.get('en') for z in par['segments']) and par['availability']=='hebrew-only','Parparos 13 HE-only')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-29.json'); req(len(prayer['segments'])==13 and [z['sourceId'] for z in prayer['segments']]==[f'p29{chr(97+i)}' for i in range(13)] and prayer['navigation']['prevUrl'] and prayer['navigation']['nextUrl'] and all(z['he'] and z['en'] and 'עברית ▾' not in z['en'] for z in prayer['segments']),'authoritative prayer')
 nn=load(BASE/'likutay-nanach.json'); sis=list(range(139,184)); req(len(nn['segments'])==45 and [z['sourceIndex'] for z in nn['segments']]==sis and all(z['he'] and not z.get('en') for z in nn['segments']) and nn['excludedHeadings']==[136,137,138,184],'bounded Nanach'); related=load(ROOT/'src/data/lm-commentaries.json')['1']['29']['related_commentaries']; nr=[z for z in related if z.get('book')=='likutay-nanach']; req(len(nr)==1 and nr[0]['sourceIndices']==sis and nr[0]['url'].endswith('/29/likutay-nanach.json'),'registry')
 manifest=load(BASE/'peer-halikutim/manifest.json'); req(manifest['sourceSha256']==SHA and manifest['hebrewBooksId']==66040 and manifest['sourcePageRange']==[65,134] and [z['sourcePage'] for z in manifest['pages']]==list(range(65,135)),'Pe’er range'); assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')}; expected_assets={f'page-{x}.webp' for x in range(65,135)}; pdf=(BASE/'peer-halikutim/peer-halikutim-torah-29.pdf').is_file(); req(not (BASE/'peer-halikutim/page-64.webp').exists() and not (BASE/'peer-halikutim/page-135.webp').exists(),'excluded pages absent')
 if args.pending_facsimiles: req(not assets and not pdf and manifest['facsimileStatus'].startswith('pending'),'pending facsimiles')
 else: req(assets==expected_assets and pdf and manifest['facsimileStatus']=='ready','facsimiles ready')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/29.astro').read_text(encoding='utf-8'); req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers'); req('75 source-audited Sefaria leaves plus one exact Classic Rashi supplement' in astro and 'pages 65–134' in astro and 'https://www.peer-halikutim.com/' in astro and '3 Hebrew-only' in astro and '13 Hebrew-only' in astro and '13 paired bilingual blocks' in astro,'route truth/credit')
 classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(encoding='utf-8'); directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(encoding='utf-8'); req(classic.count('25, 26, 27, 28, 29]')>=2 and 'length: 29' in directory and '<= 29' in directory and "'כה','כו','כז','כח','כט'" in directory,'discovery')
 print('Validated Torah 29: 75 exact bilingual leaves + 1 Classic Rashi supplement (76 records), 30 phrases across 12 sections, 9 layers, Pettek 16 asymmetric, Biur 3 HE-only, Parparos 13 HE-only, Nanach 45 HE-only, prayer 13, Pe’er 65–134; '+('facsimiles pending separately supervised conversion.' if args.pending_facsimiles else 'facsimiles ready.'))
if __name__=='__main__': main()
