#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 23 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'public/reader/super/likutay-moharan/1/23';COUNTS=[20,3,11,8,23,17,3,7,3,4,1,1,2];SHA='7d8d2adaad23ace7197ecac35b3e2055973305b832b45581c7d27fe84c76e052';AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
def load(p):return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v):return re.sub(r'\s+',' ',re.sub(r'<[^>]+>','',v or '')).strip()
def req(c,m):
 if not c:raise RuntimeError(m)
def main():
 a=argparse.ArgumentParser();a.add_argument('--pending-facsimiles',action='store_true');x=a.parse_args();study=load(BASE/'torah-study.json');s=study['segments'];req(len(s)==104 and [z['index'] for z in s]==list(range(1,105)),'104 contiguous passages');refs=[z.get('sourceRef') for z in s if not z.get('classicSupplement')];expected=[f'Likutei Moharan 23:{sec}:{leaf}' for sec,n in enumerate(COUNTS,1) for leaf in range(1,n+1)];req(refs==expected and len(refs)==103,'103 exact Sefaria refs');req(all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in s),'bilingual invariant');sup=[z for z in s if z.get('classicSupplement')];req(len(sup)==1 and sup[0]['index']==9 and sup[0]['afterSefariaRef']=='Likutei Moharan 23:1:8' and sup[0]['sefariaRef'] is None and 'silusah – placenta.]' in sup[0]['en'],'Rashi supplement');req(study['sefariaSectionCounts']==COUNTS and study['sefariaPassages']==103 and study['restoredBilingualSupplements']==1,'counts');src=study['source'];req(src['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and src['license']=='CC-BY-NC' and src['heLicense']=='Public Domain','licenses');by={z['sourceRef'].replace('Likutei Moharan ',''):z for z in s if not z.get('classicSupplement')};req('And he answered them:And he answered them:' in plain(by['23:5:9']['rawSource']['en']) and 'e st ate' in plain(by['23:5:10']['rawSource']['en']) and 'st ench' in plain(by['23:13:1']['rawSource']['en']),'source anomalies');req(all(('{' in plain(by[r]['rawSource']['en']) or '}' in plain(by[r]['rawSource']['en'])) for r in ['23:1:14','23:1:18','23:3:1','23:3:9','23:4:1','23:4:3','23:5:1','23:6:16']),'brace blocks')
 ph=load(BASE/'phrase-study.json');req(len(ph['phrases'])==30 and ph['selectedPassages'][0]==1 and ph['selectedPassages'][-1]==104,'30 phrases');idx={z['index']:z for z in s}
 for q in ph['phrases']:
  z=idx[q['segment']];req(q['source']==q['sourceRef']==z['sourceRef'] and q['he'] in plain(z['he']) and q['enMatch'] in plain(z['en']) and all(f'data-inline-phrase="{q["id"]}"' in z[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-23.json');req(len(p['segments'])==17 and p['layerAvailability']==AV,'Pettek');req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek language truth');b=load(BASE/'biur-halikutim.json');req(b['segments']==[] and b['availability']=='unavailable','Biur unavailable');par=load(BASE/'parparos-lechochma.json');req(len(par['segments'])==17 and [z['sourceIndex'] for z in par['segments']]==[2,3,5,6,8,10,12,14,16,18,20,22,24,25,27,29,31] and par['hasEnglish'] is False and all(z['he'] and not z['en'] for z in par['segments']),'Parparos');pr=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-23.json');req(len(pr['segments'])==12 and [z['sourceId'] for z in pr['segments']]==[f'p23{chr(97+i)}' for i in range(12)] and pr['navigation']['prevUrl'] and pr['navigation']['nextUrl'] and all(z['he'] and z['en'] and 'עברית ▾' not in z['en'] for z in pr['segments']),'prayer');nn=load(BASE/'likutay-nanach.json');ninds=[14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31];req(len(nn['segments'])==17 and [z['sourceIndex'] for z in nn['segments']]==ninds and all(z['he'] and not z.get('en') for z in nn['segments']),'Nanach');reg=load(ROOT/'src/data/lm-commentaries.json')['1']['23']['related_commentaries'];na=[z for z in reg if z.get('book')=='likutay-nanach'];req(len(na)==1 and na[0]['url'].endswith('/23/likutay-nanach.json') and na[0]['sourceIndices']==ninds and not any(z.get('book')=='biur-halikutim' for z in reg),'registry')
 m=load(BASE/'peer-halikutim/manifest.json');pages=m['pages'];req(m['sourceSha256']==SHA and m['hebrewBooksId']==66039 and m['sourcePageRange']==[21,112] and len(pages)==92 and [z['sourcePage'] for z in pages]==list(range(21,113)),'Pe’er manifest');assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')};expected_assets={f'page-{i}.webp' for i in range(21,113)};pdf=(BASE/'peer-halikutim/peer-halikutim-torah-23.pdf').is_file();req((not assets and not pdf) or (assets==expected_assets and pdf),'facsimile readiness');req(not x.pending_facsimiles or (not assets and not pdf and m['facsimileStatus'].startswith('pending')),'pending mode')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/23.astro').read_text();req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers');req('https://www.peer-halikutim.com/' in astro and 'Unavailable for Torah 23' in astro and 'pages 21–112' in astro,'route audit tokens');classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text();directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text();req(classic.count('23]')>=2 and 'length: 23' in directory and '<= 23' in directory,'discovery upper bound');print('Validated Torah 23: 103 Sefaria + 1 exact Rashi = 104 bilingual passages, 30 phrases, 9 layers, Pettek 17 asymmetric, Biur unavailable, Parparos 17 HE-only, Nanach 17 HE-only, prayer 12, Pe’er 21–112; '+('facsimiles ready.' if assets else 'facsimiles pending separately supervised conversion.'))
if __name__=='__main__':main()
