#!/usr/bin/env python3
"""Validate frozen Torah 21 Full Super Reader package in strict pending/ready mode."""
from __future__ import annotations
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/21'
COUNTS=[4,5,4,7,3,11,6,7,4,5,16,5,5,8,2,4,1,5]; SHA='796b49291678cc50b05f90ca0e7e2955eae62b0f2455d798ca55aa2ddb9673d3'
AVAILABILITY={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
PRIMARY=[2,3]+[5]*2+[7]*5+[9]*4+[10]*2+[11]*5+[12]*3+[13]*2+[14]*4+[15]*5+[17]*6+[19]*7+[20]*3+[21]+[22]*5+[23]*4+[24]*11+[25]+[26]*25+[27]*5
MERGED={1:[1,2],3:[4,5],5:[6,7],10:[8,9],35:[16,17],41:[18,19]}
def load(path): return json.loads(Path(path).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(value): return re.sub(r'<span[^>]*>|</span>','',value or '').strip()
def require(condition,message):
 if not condition: raise RuntimeError(message)
def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--pending-facsimiles',action='store_true'); args=parser.parse_args()
 classic=load(ROOT/'public/reader/likutay-moharan/part-1/torah-21.json'); require(len(classic.get('segments',[]))==27,'Classic physical/in-scope count must be 27')
 study=load(BASE/'torah-study.json'); segs=study.get('segments',[])
 require(len(PRIMARY)==102 and len(segs)==102 and [x.get('index') for x in segs]==list(range(1,103)),'Study must contain contiguous passages 1-102')
 refs=[f'Likutei Moharan 21:{section}:{leaf}' for section,count in enumerate(COUNTS,1) for leaf in range(1,count+1)]
 require([x.get('sourceRef') for x in segs]==refs and refs[0]=='Likutei Moharan 21:1:1' and refs[-1]=='Likutei Moharan 21:18:5','Exact 102-ref sequence mismatch')
 require(all(plain(x.get('he')) and plain(x.get('he_nikud')) and plain(x.get('en')) and plain(x['he'])!=plain(x['en']) for x in segs),'Every aligned passage must be genuinely bilingual')
 require([x.get('classicSegment') for x in segs]==PRIMARY,'Exact 27-Classic primary crosswalk mismatch')
 for index,merged in MERGED.items(): require(segs[index-1].get('classicSegments')==merged,f'Merged Classic crosswalk mismatch at passage {index}')
 require(all(not x.get('classicSegments') for i,x in enumerate(segs,1) if i not in MERGED),'Unexpected Classic heading merge')
 anomaly=segs[25]; raw_en=re.sub(r'\s+',' ',re.sub(r'<[^>]+>','',anomaly['rawSource']['en'])).strip()
 require(anomaly['sourceRef']=='Likutei Moharan 21:6:3' and anomaly['classicSegment']==14 and raw_en.startswith('{') and 'mo st tru st ed' in raw_en,'21:6:3 anomaly not preserved')
 require(study.get('sefariaSectionCounts')==COUNTS and all(study.get(k)==102 for k in ('sefariaPassages','totalPassages','productionAlignedPassages')) and study.get('restoredBilingualSupplements')==0,'Study count/restoration metadata mismatch')
 source=study.get('source',{}); expected_meta={'ref':'Likutei Moharan 21:1','prev':'Likutei Moharan 20:10','lastNext':'Likutei Moharan 22:1','versionTitle':'Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012','license':'CC-BY-NC','versionSource':'https://www.nli.org.il/he/books/NNL01','heVersionTitle':'Likutei Moharan - rabenubook.com','heLicense':'Public Domain','heVersionSource':'http://rabenubook.com/%D7%9C%D7%99%D7%A7%D7%95%D7%98%D7%99-%D7%9E%D7%95%D7%94%D7%A8%D7%B4%D7%9F-%D7%90/'}
 require(all(source.get(k)==v for k,v in expected_meta.items()),'Sefaria provenance mismatch'); require('editionClose' not in study and not any(x.get('insertedSupplement') for x in segs),'Synthetic restoration must be absent')
 phrases=load(BASE/'phrase-study.json'); plist=phrases.get('phrases',[]); selected=phrases.get('selectedPassages',[])
 require(len(plist)==30 and len({x['id'] for x in plist})==30 and len(set(selected))==30 and selected[0]==1 and selected[-1]==102,'30-phrase distribution mismatch')
 by_index={x['index']:x for x in segs}
 for phrase in plist:
  segment=by_index[int(phrase['segment'])]; require(all(str(phrase.get(k,'')).strip() for k in ('he','en','enMatch','info','source','sourceRef')),f'Incomplete phrase {phrase.get("id")}'); require(phrase['source']==segment['sourceRef'] and phrase['he'] in plain(segment['he']) and phrase['enMatch'] in plain(segment['en']),f'Phrase source mismatch: {phrase.get("id")}'); require(all(f'data-inline-phrase="{phrase["id"]}"' in segment[k] for k in ('he','he_nikud','en')),f'Phrase markers missing: {phrase["id"]}')
 pettek=load(ROOT/'public/reader/pettek-nanach-commentary/torah-21.json'); psegments=pettek.get('segments',[])
 require(len(psegments)==27 and [int(x['index']) for x in psegments]==list(range(1,28)) and [int(x['relatedSegment']) for x in psegments]==list(range(1,28)) and pettek.get('layerAvailability')==AVAILABILITY,'Pettek count/availability mismatch')
 for item in psegments:
  actual={layer:{lang:bool(str((item.get('layers',{}).get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AVAILABILITY}; require(actual==AVAILABILITY,f'Pettek asymmetric language mismatch at {item.get("index")}'); expected=[i for i,primary in enumerate(PRIMARY,1) if primary==item['relatedSegment'] or item['relatedSegment'] in MERGED.get(i,[])]; require(item.get('alignedPassages')==expected and item.get('alignedPassage')==expected[0],f'Pettek crosswalk mismatch at {item.get("index")}')
 biur=load(ROOT/'public/reader/biur-halikutim/section-26.json'); bsegs=biur.get('segments',[]); require(biur.get('sourceSection')==26 and biur.get('displayNumber')==21 and len(bsegs)==210 and [x['index'] for x in bsegs]==list(range(1,211)) and biur.get('hasEnglish') is False and all(x.get('he') and not x.get('en') for x in bsegs),'Biur section 26 Hebrew-only package mismatch')
 parparos=load(BASE/'parparos-lechochma.json'); psegs=parparos.get('segments',[]); require(parparos.get('sourceSection')==22 and len(psegs)==20 and [x['index'] for x in psegs]==list(range(1,21)) and [x['sourceIndex'] for x in psegs]==list(range(2,41,2)) and parparos.get('hasEnglish') is False and all(x.get('he') and not x.get('en') for x in psegs),'Parparos normalization/language mismatch')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-21.json'); qsegs=prayer.get('segments',[]); ids=[f'p21{chr(97+i)}' for i in range(13)]; require(len(qsegs)==13 and [x['index'] for x in qsegs]==list(range(1,14)) and [x['sourceId'] for x in qsegs]==ids and prayer.get('totalParagraphs')==13,'Prayer p21a-p21m mismatch'); require(prayer.get('navigation',{}).get('prevUrl')=='/reader/likutay-tefilos/1/20' and prayer.get('navigation',{}).get('nextUrl')=='/reader/likutay-tefilos/1/22','Prayer navigation regression'); excluded=prayer.get('excludedMetadata',{}); require(excluded.get('dateBars')==4 and excluded.get('specialBars')==2 and all(x.get('he') and x.get('en') for x in qsegs),'Prayer blocks/bar metadata mismatch')
 nanach=load(BASE/'likutay-nanach.json'); nsegs=nanach.get('segments',[]); require(len(nsegs)==25 and [(x.get('sourceFile'),x.get('sourceIndex')) for x in nsegs]==[('volume-4/chapter-18.json',i) for i in range(28,53)] and all(x.get('he') and not x.get('en') for x in nsegs),'Nanach chapter 18 Hebrew-only range mismatch'); require(any(x.get('sourceIndex')==49 for x in nsegs),'Nanach index 49 missing')
 associations=load(ROOT/'src/data/lm-commentaries.json')['1']['21']['related_commentaries']; n_assoc=[x for x in associations if x.get('book')=='likutay-nanach']; require(len(n_assoc)==1 and n_assoc[0].get('url')=='/reader/likutay-nanach/volume-4/chapter-18.json' and n_assoc[0].get('sourceRange')=={'startIndex':28,'endIndex':52,'count':25},'Nanach discovery association mismatch')
 manifest=load(BASE/'peer-halikutim/manifest.json'); require(manifest.get('hebrewBooksId')==66038 and manifest.get('sourceSha256')==SHA and manifest.get('sourcePageRange')==[301,412] and len(manifest.get('pages',[]))==112 and [x['sourcePage'] for x in manifest['pages']]==list(range(301,413)),'Pe’er constants/range mismatch'); require(manifest.get('pdf')=='/reader/super/likutay-moharan/1/21/peer-halikutim/peer-halikutim-torah-21.pdf' and all(x.get('image')==f'/reader/super/likutay-moharan/1/21/peer-halikutim/page-{x["sourcePage"]}.webp' for x in manifest['pages']),'Pe’er public paths mismatch'); require('page 413 begins Torah 22' in manifest.get('textNotice','') and all('page-413.webp' not in x.get('image','') for x in manifest['pages']),'Pe’er exclusion mismatch')
 expected_assets={f'page-{n}.webp' for n in range(301,413)}; actual_assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')}; pdf_ready=(BASE/'peer-halikutim/peer-halikutim-torah-21.pdf').is_file(); require((not actual_assets and not pdf_ready) or (actual_assets==expected_assets and pdf_ready),'Pe’er asset readiness mismatch'); require(not args.pending_facsimiles or (not actual_assets and not pdf_ready and manifest.get('facsimileStatus')=='pending-separately-supervised-conversion'),'Explicit pending mode requires no facsimile artifacts and pending manifest')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/21.astro').read_text(encoding='utf-8'); layers=set(re.findall(r'data-open-source="([^"]+)"',astro)); require(layers=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},f'Expected nine study layers, got {sorted(layers)}')
 for token in ('<span><b>9</b> study layers</span>','exactly 102 Hebrew leaves','21:6:3','corrupted 27 legacy Classic alignments','beginner English-only','source section 26 · 210 Hebrew-only records','source section 22 · 20 Hebrew-only records','chapter 18 indices 28–52','13 bilingual blocks p21a–p21m','Pe’er pages 301–412','page 413 begins Torah 22','https://www.peer-halikutim.com/'):
  require(token in astro,f'Route source-integrity token missing: {token}')
 classic_page=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(encoding='utf-8-sig').replace('\x00',''); part_directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(encoding='utf-8-sig').replace('\x00',''); book_directory=(ROOT/'src/pages/reader/likutay-moharan/index.astro').read_text(encoding='utf-8-sig').replace('\x00',''); require('[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]' in classic_page,'Classic route integration missing'); require('Array.from({ length: 21 }' in part_directory and 'Number(item.number) <= 21' in part_directory and '/reader/super/likutay-moharan/1/${number}' in part_directory,'Part directory spotlight/badge integration missing'); require("Astro.redirect('/reader/likutay-moharan/1/'" in book_directory,'Book directory redirect changed')
 status='facsimiles pending separately supervised conversion' if not actual_assets else 'facsimiles ready'; print('Validated Torah 21: 102 Sefaria bilingual leaves across 18 sections, exact 27-Classic crosswalk with 21:6:3 preserved and no synthetic restoration, 30 exact bilingual phrases, 9 study layers, Pettek 27 asymmetric, Biur 210, Parparos 20 Hebrew-only, Nanach 25, prayer 13, Pe’er pages 301–412; '+status+'.')
if __name__=='__main__': main()
