#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 31 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/31'; SHA='f831b7a589474499ea1e6b7241ee0a5ed1b910148324449210209760a48792b7'; COUNTS=[5,7,2,4,6,5,3,4,9,9,3,8,11,4,10,2,10,6]
AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
EXPECTED={1:[1],2:[2],3:[3],4:list(range(3,7)),5:[7],6:list(range(8,14)),7:list(range(14,16)),8:list(range(16,20)),9:list(range(20,23)),10:[23],11:list(range(24,26)),12:list(range(26,31)),13:list(range(31,34)),14:list(range(34,38)),15:list(range(38,47)),16:list(range(47,54)),17:list(range(54,56)),18:list(range(56,59)),19:list(range(59,72)),20:list(range(71,78)),21:list(range(78,82)),22:list(range(82,92)),23:list(range(92,94)),24:list(range(94,108)),25:[108,109],26:[109]}
def load(p): return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',v or '')).strip()
def req(c,m):
 if not c: raise RuntimeError(m)
def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--pending-facsimiles',action='store_true'); args=parser.parse_args(); study=load(BASE/'torah-study.json'); segs=study['segments']; refs=[f'Likutei Moharan 31:{s}:{l}' for s,n in enumerate(COUNTS,1) for l in range(1,n+1)]
 req(len(segs)==109 and [z['index'] for z in segs]==list(range(1,110)),'109 display records'); paired=[z for z in segs if isinstance(z.get('sourceComment'),int)]; req([z['sourceRef'] for z in paired]==refs,'exact Sefaria refs'); req(len(paired)==108 and all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in paired),'bilingual witness invariant'); req(study['productionAlignedPassages']==109 and study['productionDisplayRecords']==109 and study['sefariaPassages']==108 and study['sefariaSectionCounts']==COUNTS and study['restoredBilingualSupplements']==1 and study['structuralRestorations']==0,'counts')
 source=study['source']; req(source['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and source['license']=='CC-BY-NC' and source['versionSource']=='https://www.nli.org.il/he/books/NNL01','English license'); req(source['heVersionTitle']=='Likutei Moharan - rabenubook.com' and source['heLicense']=='Public Domain' and source['prev']=='Likutei Moharan 30:10' and source['lastNext']=='Likutei Moharan 32:1','Hebrew license/boundaries'); req(segs[0]['sourceRef']=='Likutei Moharan 31:1:1' and segs[-1]['sourceRef']=='Likutei Moharan 31:18:6' and 'אית לן בירא' in plain(segs[0]['he']) and 'ropesout' in plain(segs[0]['en']) and 'thereanyone' in plain(segs[0]['en']),'anchors/source typos'); supplement=segs[1]; req(supplement['supplementType']=='bilingual-classic-rashi-supplement' and supplement['classicSourceIndices']==[1,2,3] and supplement['classicSegments']==[2] and plain(supplement['he']).startswith('רש"י: דפארי. סבין') and plain(supplement['en'])=='[Rashi: פָּארֵי – parai is bran. Make for me a rope from bran. And if you do not fulfill my request, I too will not fulfill your request.]','Classic bilingual supplement'); req('אמן כן יהי רצון' in plain(segs[-1]['he']) and 'Praise to the Living God' in plain(segs[-1]['en']),'final anchor')
 by={i:[z['index'] for z in segs if i in set(map(int,z.get('classicSegments',[z['classicSegment']]))) ] for i in range(1,27)}; req(by==EXPECTED,'classic crosswalk'); req(segs[2]['classicSegments']==[3,4] and segs[2]['classicSegment']==4 and [19,20]==segs[70]['classicSegments'] and [25,26]==segs[108]['classicSegments'],'merged Classic boundaries')
 phrases=load(BASE/'phrase-study.json'); req(len(phrases['phrases'])==30 and phrases['representedSections']==list(range(1,19)),'30 phrases/18 sections'); req(len(phrases['selectedPassages'])==18 and len(set(phrases['selectedPassages']))==18,'selected passages')
 for phrase in phrases['phrases']:
  seg=segs[int(phrase['segment'])-1]; req(phrase['source']==phrase['sourceRef']==seg['sourceRef'],'phrase provenance'); req(phrase['he'] in plain(seg['he']) and phrase['enMatch'] in plain(seg['en']),'exact phrase text'); req(all(f'data-inline-phrase="{phrase["id"]}"' in seg[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-31.json'); req(len(p['segments'])==26 and p['layerAvailability']==AV,'Pettek count/availability'); req([z['alignedPassages'] for z in p['segments']]==[EXPECTED[i] for i in range(1,27)],'Pettek crosswalk'); req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek language truth')
 biur=load(BASE/'biur-halikutim.json'); req(len(biur['segments'])==4 and [z['sourceIndex'] for z in biur['segments']]==[86,87,88,89] and all(z['he'] and not z.get('en') for z in biur['segments']) and biur['availability']=='hebrew-only' and biur['excludedMisfiledFile'].endswith('section-31.json'),'Biur 4 HE-only anomaly'); par=load(BASE/'parparos-lechochma.json'); pi=list(range(2,27,2)); req(len(par['segments'])==13 and par['sourceIndices']==pi and all(z['he'] and not z.get('en') for z in par['segments']) and par['availability']=='hebrew-only','Parparos 13 HE-only')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-31.json'); ids=[f'p31{chr(97+i)}' for i in range(18)]; req(len(prayer['segments'])==18 and [z['assignedPackageId'] for z in prayer['segments']]==ids and prayer['assignedPackageIds']==ids and prayer['navigation']['prevUrl'] and prayer['navigation']['nextUrl'] and prayer['excludedMetadata']['dateBars']==4 and all(z['he'] and z['en'] and 'עברית ▾' not in z['en'] for z in prayer['segments']),'authoritative prayer'); req((ROOT/'public/teachings/likutay-tefilos/likutay_tefilos_31_prayer31.html').is_file(),'copied authoritative prayer HTML')
 nn=load(BASE/'likutay-nanach.json'); identities=[('volume-4/chapter-25.json',i) for i in range(223,241)]+[('volume-4/chapter-26.json',i) for i in range(1,67)]; req(len(nn['segments'])==84 and [(z['sourceFile'],z['sourceIndex']) for z in nn['segments']]==identities and all(z['he'] and not z.get('en') for z in nn['segments']) and nn['excludedHeadings']==[{'file':'volume-4/chapter-25.json','index':222},{'file':'volume-4/chapter-26.json','index':67}],'bounded two-file Nanach'); related=load(ROOT/'src/data/lm-commentaries.json')['1']['31']['related_commentaries']; nr=[z for z in related if z.get('book')=='likutay-nanach']; req(len(nr)==1 and nr[0]['totalRecords']==84 and nr[0]['url'].endswith('/31/likutay-nanach.json') and len(nr[0]['sourceIdentities'])==84,'registry')
 manifest=load(BASE/'peer-halikutim/manifest.json'); req(manifest['sourceSha256']==SHA and manifest['hebrewBooksId']==66040 and manifest['sourcePageRange']==[238,351] and [z['sourcePage'] for z in manifest['pages']]==list(range(238,352)),'Pe’er range'); assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')}; expected_assets={f'page-{x}.webp' for x in range(238,352)}; pdf=(BASE/'peer-halikutim/peer-halikutim-torah-31.pdf').is_file(); req(not (BASE/'peer-halikutim/page-237.webp').exists() and not (BASE/'peer-halikutim/page-352.webp').exists(),'excluded pages absent')
 if args.pending_facsimiles: req(not assets and not pdf and manifest['facsimileStatus'].startswith('pending'),'pending facsimiles')
 else: req(assets==expected_assets and pdf and manifest['facsimileStatus']=='ready','facsimiles ready')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/31.astro').read_text(encoding='utf-8'); req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers'); req('108 bilingual leaves across sections 31:1–18' in astro and 'pages 238–351' in astro and 'https://www.peer-halikutim.com/' in astro and '4 Hebrew-only' in astro and '13 Hebrew-only' in astro and '18 paired bilingual blocks' in astro,'route truth/credit')
 classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(encoding='utf-8'); directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(encoding='utf-8'); req(classic.count('29, 30, 31]')>=2 and 'length: 31' in directory and '<= 31' in directory and "'כט','ל','לא'" in directory,'discovery')
 print('Validated Torah 31: 108 exact bilingual leaves + 1 exact bilingual Classic Rashi supplement (109 records), 30 phrases across 18 sections, 9 layers, Pettek 26 asymmetric, Biur 4 HE-only, Parparos 13 HE-only, Nanach 84 HE-only, prayer 18, Pe’er 238–351; '+('facsimiles pending separately supervised conversion.' if args.pending_facsimiles else 'facsimiles ready.'))
if __name__=='__main__': main()
