#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 28 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/28'; SHA='f831b7a589474499ea1e6b7241ee0a5ed1b910148324449210209760a48792b7'; COUNTS=[6,4,4,7,5,10]
AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
EXPECTED={1:[1],2:[1],3:list(range(2,7)),4:list(range(7,11)),5:list(range(11,15)),6:list(range(15,27)),7:list(range(27,37))}
def load(p): return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',v or '')).strip()
def req(c,m):
 if not c: raise RuntimeError(m)
def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--pending-facsimiles',action='store_true'); args=parser.parse_args(); study=load(BASE/'torah-study.json'); segs=study['segments']; refs=[f'Likutei Moharan 28:{s}:{l}' for s,n in enumerate(COUNTS,1) for l in range(1,n+1)]
 req(len(segs)==36 and [z['index'] for z in segs]==list(range(1,37)),'36 display records'); req([z['sourceRef'] for z in segs]==refs,'exact refs'); req(all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in segs),'bilingual witness invariant'); req(study['productionAlignedPassages']==36 and study['productionDisplayRecords']==36 and study['sefariaSectionCounts']==COUNTS and study['structuralRestorations']==0,'counts')
 source=study['source']; req(source['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and source['license']=='CC-BY-NC' and source['versionSource']=='https://www.nli.org.il/he/books/NNL01','English license'); req(source['heVersionTitle']=='Likutei Moharan - rabenubook.com' and source['heLicense']=='Public Domain' and source['prev']=='Likutei Moharan 27:10' and source['lastNext']=='Likutei Moharan 29:1','Hebrew license/boundaries'); req(segs[0]['sourceRef']=='Likutei Moharan 28:1:1' and segs[-1]['sourceRef']=='Likutei Moharan 28:6:10' and 'בני לן ביתא' in plain(segs[0]['he']),'anchors')
 by={i:[z['index'] for z in segs if int(z['classicSegment'])==i] for i in (1,3,4,5,6,7)}; req(by=={1:[1],3:list(range(2,7)),4:list(range(7,11)),5:list(range(11,15)),6:list(range(15,27)),7:list(range(27,37))},'classic crosswalk')
 phrases=load(BASE/'phrase-study.json'); req(len(phrases['phrases'])==30 and phrases['representedSections']==list(range(1,7)),'30 phrases/6 sections'); req(len(phrases['selectedPassages'])==6 and len(set(phrases['selectedPassages']))==6,'selected passages')
 for phrase in phrases['phrases']:
  seg=segs[int(phrase['segment'])-1]; req(phrase['source']==phrase['sourceRef']==seg['sourceRef'],'phrase provenance'); req(phrase['he'] in plain(seg['he']) and phrase['enMatch'] in plain(seg['en']),'exact phrase text'); req(all(f'data-inline-phrase="{phrase["id"]}"' in seg[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-28.json'); req(len(p['segments'])==7 and p['layerAvailability']==AV,'Pettek count/availability'); req([z['alignedPassages'] for z in p['segments']]==[EXPECTED[i] for i in range(1,8)],'Pettek crosswalk'); req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek language truth')
 biur=load(BASE/'biur-halikutim.json'); req(len(biur['segments'])==1 and biur['segments'][0]['sourceIndex']==1 and biur['segments'][0]['he'] and not biur['segments'][0].get('en') and biur['availability']=='hebrew-only','Biur 1 HE-only'); par=load(BASE/'parparos-lechochma.json'); req(len(par['segments'])==4 and par['sourceIndices']==[2,4,6,8] and all(z['he'] and not z.get('en') for z in par['segments']) and par['availability']=='hebrew-only','Parparos 4 HE-only')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-28.json'); req(len(prayer['segments'])==5 and [z['sourceId'] for z in prayer['segments']]==[f'p28{chr(97+i)}' for i in range(5)] and prayer['navigation']['prevUrl'] and prayer['navigation']['nextUrl'] and all(z['he'] and z['en'] and 'עברית ▾' not in z['en'] for z in prayer['segments']),'authoritative prayer')
 nn=load(BASE/'likutay-nanach.json'); sis=list(range(84,128))+list(range(129,136))+[137]; req(len(nn['segments'])==52 and [z['sourceIndex'] for z in nn['segments']]==sis and all(z['he'] and not z.get('en') for z in nn['segments']) and nn['excludedHeadings']==[83,128,136,138],'bounded Nanach'); related=load(ROOT/'src/data/lm-commentaries.json')['1']['28']['related_commentaries']; nr=[z for z in related if z.get('book')=='likutay-nanach']; req(len(nr)==1 and nr[0]['sourceIndices']==sis and nr[0]['url'].endswith('/28/likutay-nanach.json'),'registry')
 manifest=load(BASE/'peer-halikutim/manifest.json'); req(manifest['sourceSha256']==SHA and manifest['hebrewBooksId']==66040 and manifest['sourcePageRange']==[21,64] and [z['sourcePage'] for z in manifest['pages']]==list(range(21,65)),'Pe’er range'); assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')}; expected_assets={f'page-{x}.webp' for x in range(21,65)}; pdf=(BASE/'peer-halikutim/peer-halikutim-torah-28.pdf').is_file(); req(not (BASE/'peer-halikutim/page-20.webp').exists() and not (BASE/'peer-halikutim/page-65.webp').exists(),'excluded pages absent')
 if args.pending_facsimiles: req(not assets and not pdf and manifest['facsimileStatus'].startswith('pending'),'pending facsimiles')
 else: req(assets==expected_assets and pdf and manifest['facsimileStatus']=='ready','facsimiles ready')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/28.astro').read_text(encoding='utf-8'); req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers'); req('36 source-audited Sefaria leaves' in astro and 'pages 21–64' in astro and 'https://www.peer-halikutim.com/' in astro and '1 Hebrew-only' in astro and '4 Hebrew-only' in astro and '5 paired bilingual blocks' in astro,'route truth/credit')
 classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(encoding='utf-8'); directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(encoding='utf-8'); req(classic.count('25, 26, 27, 28]')>=2 and 'length: 28' in directory and '<= 28' in directory and "'כה','כו','כז','כח'" in directory,'discovery')
 print('Validated Torah 28: 36 exact bilingual leaves, 30 phrases across 6 sections, 9 layers, Pettek 7 asymmetric, Biur 1 HE-only, Parparos 4 HE-only, Nanach 52 HE-only, prayer 5, Pe’er 21–64; '+('facsimiles pending separately supervised conversion.' if args.pending_facsimiles else 'facsimiles ready.'))
if __name__=='__main__': main()
