#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 24 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'public/reader/super/likutay-moharan/1/24';COUNTS=[3,5,2,3,3,4,3,5,7,10];SHA='7d8d2adaad23ace7197ecac35b3e2055973305b832b45581c7d27fe84c76e052';AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
def load(p):return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v):return re.sub(r'\s+',' ',re.sub(r'<[^>]+>','',v or '')).strip()
def req(c,m):
 if not c:raise RuntimeError(m)
def main():
 a=argparse.ArgumentParser();a.add_argument('--pending-facsimiles',action='store_true');x=a.parse_args();st=load(BASE/'torah-study.json');s=st['segments'];refs=[f'Likutei Moharan 24:{sec}:{leaf}' for sec,n in enumerate(COUNTS,1) for leaf in range(1,n+1)];req(len(s)==45 and [z['index'] for z in s]==list(range(1,46)) and [z['sourceRef'] for z in s]==refs,'45 exact refs');req(all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in s),'bilingual invariant');req(st['sefariaSectionCounts']==COUNTS and st['productionAlignedPassages']==st['sefariaPassages']==45 and st['productionDisplayRecords']==46 and st['structuralRestorations']==1,'counts');notes=st['structuralNotes'];req(notes==[{'type':'structuralNote','afterAlignedPassage':1,'classicSegment':2,'he':'(לשון רבנו זכרונו לברכה):','en':None,'source':'/reader/likutay-moharan/part-1/torah-24.json#segment-2'}],'structural note');src=st['source'];req(src['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and src['license']=='CC-BY-NC' and src['heLicense']=='Public Domain','licenses');by={z['sourceRef'].replace('Likutei Moharan ',''):z for z in s};req('{' in plain(by['24:9:1']['rawSource']['en']) and '}' in plain(by['24:9:7']['rawSource']['en']) and all(('{' not in plain(by[f'24:9:{i}']['rawSource']['en']) and '}' not in plain(by[f'24:9:{i}']['rawSource']['en'])) for i in range(2,7)),'brace spanning block')
 ph=load(BASE/'phrase-study.json');req(len(ph['phrases'])==30 and ph['selectedPassages'][0]==1 and ph['selectedPassages'][-1]==45,'phrases');idx={z['index']:z for z in s}
 for q in ph['phrases']:
  z=idx[q['segment']];req(q['source']==q['sourceRef']==z['sourceRef'] and q['he'] in plain(z['he']) and q['enMatch'] in plain(z['en']) and all(f'data-inline-phrase="{q["id"]}"' in z[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-24.json');req(len(p['segments'])==12 and p['layerAvailability']==AV and p['segments'][1]['structuralNote']==0,'Pettek');req(all({l:{k:bool(str((z['layers'].get(l) or {}).get(k) or '').strip()) for k in ('he','en')} for l in AV}==AV for z in p['segments']),'language truth');b=load(BASE/'biur-halikutim.json');req(not b['segments'] and b['availability']=='unavailable','Biur');par=load(BASE/'parparos-lechochma.json');req(len(par['segments'])==15 and [z['sourceIndex'] for z in par['segments']]==list(range(2,31,2)) and all(z['he'] and not z['en'] for z in par['segments']),'Parparos');pr=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-24.json');req(len(pr['segments'])==4 and [z['sourceId'] for z in pr['segments']]==['p24a','p24b','p24c','p24d'] and pr['navigation']['prevUrl'] and pr['navigation']['nextUrl'] and all(z['he'] and z['en'] and 'עברית ▾' not in z['en'] for z in pr['segments']),'prayer');nn=load(BASE/'likutay-nanach.json');ninds=[33,35,36,37,38,39,40,41];req(len(nn['segments'])==8 and [z['sourceIndex'] for z in nn['segments']]==ninds and all(z['he'] and not z.get('en') for z in nn['segments']),'Nanach');rel=load(ROOT/'src/data/lm-commentaries.json')['1']['24']['related_commentaries'];na=[z for z in rel if z.get('book')=='likutay-nanach'];req(len(na)==1 and na[0]['sourceIndices']==ninds and na[0]['url'].endswith('/24/likutay-nanach.json') and not any(z.get('book')=='biur-halikutim' for z in rel),'registry')
 m=load(BASE/'peer-halikutim/manifest.json');req(m['sourceSha256']==SHA and m['hebrewBooksId']==66039 and m['sourcePageRange']==[113,173] and [z['sourcePage'] for z in m['pages']]==list(range(113,174)),'Pe’er');assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')};exp={f'page-{i}.webp' for i in range(113,174)};pdf=(BASE/'peer-halikutim/peer-halikutim-torah-24.pdf').is_file();req((not assets and not pdf) or (assets==exp and pdf),'assets');req(not x.pending_facsimiles or (not assets and not pdf and m['facsimileStatus'].startswith('pending')),'pending')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/24.astro').read_text();req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers');req('sr-structural-note' in astro and 'Unavailable for Torah 24' in astro and 'pages 113–173' in astro and 'https://www.peer-halikutim.com/' in astro,'route');classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text();directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text();req(classic.count('24]')>=2 and 'length: 24' in directory and '<= 24' in directory,'discovery');print('Validated Torah 24: 45 bilingual leaves + 1 Hebrew-only structural note, 30 phrases, 9 layers, Pettek 12 asymmetric, Biur unavailable, Parparos 15 HE-only, Nanach 8 HE-only, prayer 4, Pe’er 113–173; '+('facsimiles ready.' if assets else 'facsimiles pending separately supervised conversion.'))
if __name__=='__main__':main()
