#!/usr/bin/env python3
"""Validate frozen Torah 22 Full Super Reader package in strict pending/ready mode."""
from __future__ import annotations
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/22'
COUNTS=[8,6,2,6,11,3,7,3,7,23,6,9,12,4,1,1,1,1,1,1,11]
SHA='796b49291678cc50b05f90ca0e7e2955eae62b0f2455d798ca55aa2ddb9673d3'
AVAILABILITY={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
RANGES=[('volume-4/chapter-19.json',1,15),('volume-4/chapter-20.json',1,1),('volume-4/chapter-21.json',1,2),('volume-4/chapter-22.json',1,1),('volume-4/chapter-23.json',1,1),('volume-4/chapter-24.json',1,1),('volume-4/chapter-25.json',1,12)]
CROSSWALK=[(1,1,1),(2,2,2),(3,8,3),(9,14,4),(15,16,5),(17,22,6),(23,33,7),(34,36,8),(37,43,9),(44,46,10),(47,47,11),(48,53,12),(54,60,13),(61,76,14),(77,82,15),(83,91,16),(92,106,17),(107,107,18),(108,108,19),(109,109,20),(110,110,21),(111,111,22),(112,112,23),(113,113,24),(114,116,25),(117,117,26),(118,124,27)]
PRIMARY=[classic for first,last,classic in CROSSWALK for _ in range(first,last+1)]
PARPAROS=[2,4,6,8,10,12,14,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53]
def load(path): return json.loads(Path(path).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(value): return re.sub(r'\s+',' ',re.sub(r'<[^>]+>','',value or '')).strip()
def sourced(value): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',value or '')).strip()
def require(condition,message):
 if not condition: raise RuntimeError(message)
def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--pending-facsimiles',action='store_true'); args=parser.parse_args()
 classic=load(ROOT/'public/reader/likutay-moharan/part-1/torah-22.json'); require(len(classic.get('segments',[]))==27 and len(classic.get('aligned_segments',[]))==27,'Classic physical/legacy pair count must be 27')
 study=load(BASE/'torah-study.json'); segs=study.get('segments',[])
 require(len(PRIMARY)==124 and len(segs)==124 and [x.get('index') for x in segs]==list(range(1,125)),'Study must contain contiguous passages 1–124')
 refs=[f'Likutei Moharan 22:{section}:{leaf}' for section,count in enumerate(COUNTS,1) for leaf in range(1,count+1)]
 require([x.get('sourceRef') for x in segs]==refs and refs[0]=='Likutei Moharan 22:1:1' and refs[-1]=='Likutei Moharan 22:21:11','Exact 124-ref sequence mismatch')
 require(all(plain(x.get('he')) and plain(x.get('he_nikud')) and plain(x.get('en')) and plain(x['he'])!=plain(x['en']) for x in segs),'Every aligned passage must be genuinely bilingual')
 require([x.get('classicSegment') for x in segs]==PRIMARY and not any(x.get('classicSegments') for x in segs),'Exact 27-Classic crosswalk mismatch')
 require(study.get('sefariaSectionCounts')==COUNTS and study.get('sefariaSections')==21 and all(study.get(k)==124 for k in ('sefariaPassages','totalPassages','productionAlignedPassages')) and study.get('classicFileSegments')==study.get('classicInScopeSegments')==27 and study.get('restoredBilingualSupplements')==0,'Study count/restoration metadata mismatch')
 source=study.get('source',{}); expected_meta={'ref':'Likutei Moharan 22:1','prev':'Likutei Moharan 21:18','lastNext':'Likutei Moharan 23:1','versionTitle':'Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012','license':'CC-BY-NC','versionSource':'https://www.nli.org.il/he/books/NNL01','heVersionTitle':'Likutei Moharan - rabenubook.com','heLicense':'Public Domain','heVersionSource':'http://rabenubook.com/%D7%9C%D7%99%D7%A7%D7%95%D7%98%D7%99-%D7%9E%D7%95%D7%94%D7%A8%D7%B4%D7%9F-%D7%90/'}
 require(all(source.get(k)==v for k,v in expected_meta.items()),'Sefaria provenance mismatch'); require('editionClose' not in study and not any(x.get('insertedSupplement') for x in segs),'Synthetic restoration must be absent')
 by_ref={x['sourceRef'].replace('Likutei Moharan ',''):x for x in segs}; brace_refs=['22:2:4','22:2:6','22:7:2','22:7:6','22:9:7','22:10:3','22:10:13','22:10:15','22:12:1','22:12:2','22:12:3','22:13:1','22:13:3']
 require(all(('{' in plain(by_ref[ref]['rawSource']['en']) or '}' in plain(by_ref[ref]['rawSource']['en'])) for ref in brace_refs),'Audited brace-delimited editorial blocks not preserved')
 anomaly=by_ref['22:13:1']; raw_en=plain(anomaly['rawSource']['en']); require(plain(anomaly['rawSource']['he'])=='וְזֶה פֵּרוּשׁ:' and len(raw_en)==985 and '{Elazar the Small' in raw_en and anomaly['classicSegment']==17,'22:13:1 anomaly not preserved')
 for ref,needle in [('22:7:2','again st us'),('22:7:6','one st anding outside'),('22:12:1','de st ined'),('22:12:1','con st ruct')]: require(needle in plain(by_ref[ref]['rawSource']['en']),f'{ref} visible source typo missing: {needle}')
 require(by_ref['22:14:4']['classicSegment']==18 and 'השמטות' in plain(by_ref['22:14:4']['he']) and all(by_ref[f'22:21:{i}']['en'] for i in range(5,12)),'Sefaria addenda/final Aramaic bilingual close mismatch')
 phrases=load(BASE/'phrase-study.json'); plist=phrases.get('phrases',[]); selected=phrases.get('selectedPassages',[]); require(len(plist)==30 and len({x['id'] for x in plist})==30 and len(set(selected))==30 and selected[0]==1 and selected[-1]==124,'30-phrase distribution mismatch')
 by_index={x['index']:x for x in segs}
 for phrase in plist:
  segment=by_index[int(phrase['segment'])]; require(all(str(phrase.get(k,'')).strip() for k in ('he','en','enMatch','info','source','sourceRef')),f'Incomplete phrase {phrase.get("id")}'); require(phrase['source']==phrase['sourceRef']==segment['sourceRef'] and phrase['he'] in sourced(segment['he']) and phrase['enMatch'] in sourced(segment['en']),f'Phrase source mismatch: {phrase.get("id")}'); require(all(f'data-inline-phrase="{phrase["id"]}"' in segment[k] for k in ('he','he_nikud','en')),f'Phrase markers missing: {phrase["id"]}')
 pettek=load(ROOT/'public/reader/pettek-nanach-commentary/torah-22.json'); psegments=pettek.get('segments',[]); require(len(psegments)==27 and [int(x['index']) for x in psegments]==list(range(1,28)) and [int(x['relatedSegment']) for x in psegments]==list(range(1,28)) and pettek.get('layerAvailability')==AVAILABILITY,'Pettek count/availability mismatch')
 for item in psegments:
  actual={layer:{lang:bool(str((item.get('layers',{}).get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AVAILABILITY}; require(actual==AVAILABILITY,f'Pettek asymmetric language mismatch at {item.get("index")}'); expected=[i for i,primary in enumerate(PRIMARY,1) if primary==item['relatedSegment']]; require(item.get('alignedPassages')==expected and item.get('alignedPassage')==expected[0],f'Pettek crosswalk mismatch at {item.get("index")}')
 shared=load(ROOT/'public/reader/biur-halikutim/section-26.json'); shared_segs=shared.get('segments',[]); require(shared.get('title')=='עתיקא טמיר וסתים-סימן כ"א' and shared.get('id')=='bhl-21' and shared.get('torah')==shared.get('displayNumber')==21 and len(shared_segs)==210 and [x['index'] for x in shared_segs]==list(range(1,211)) and shared.get('hasEnglish') is False and all(x.get('he') and not x.get('en') for x in shared_segs),'Shared Torah 21 Biur source was damaged')
 require('חותם בתוך חותם' in shared_segs[141]['he'] and shared_segs[140]['he'] and shared_segs[209]['he'],'Shared Biur physical boundaries mismatch')
 biur=load(BASE/'biur-halikutim.json'); bsegs=biur.get('segments',[]); require(biur.get('torah')==22 and biur.get('sourceSection')==26 and len(bsegs)==68 and [x['index'] for x in bsegs]==list(range(1,69)) and [x['sourceIndex'] for x in bsegs]==list(range(143,211)) and biur.get('hasEnglish') is False and all(x.get('he') and not x.get('en') for x in bsegs),'Biur Torah 22 slice mismatch'); require(all(x['he']==shared_segs[x['sourceIndex']-1]['he'].strip() for x in bsegs),'Biur package diverges from shared source')
 parparos=load(BASE/'parparos-lechochma.json'); psegs=parparos.get('segments',[]); require(parparos.get('sourceSection')==23 and len(psegs)==27 and [x['index'] for x in psegs]==list(range(1,28)) and [x['sourceIndex'] for x in psegs]==PARPAROS and parparos.get('totalParagraphs')==27 and parparos.get('hasEnglish') is False and all(x.get('he') and not x.get('en') for x in psegs),'Parparos normalization/language mismatch'); require(not psegs[7]['he'].startswith('אות'),'Parparos continuation source index 15 was not retained in place')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-22.json'); qsegs=prayer.get('segments',[]); ids=[f'p22{chr(97+i)}' for i in range(17)]; require(len(qsegs)==17 and [x['index'] for x in qsegs]==list(range(1,18)) and [x['sourceId'] for x in qsegs]==ids and prayer.get('totalParagraphs')==17,'Prayer p22a–p22q mismatch'); require(prayer.get('navigation',{}).get('prevUrl')=='/reader/likutay-tefilos/1/21' and prayer.get('navigation',{}).get('nextUrl')=='/reader/likutay-tefilos/1/23','Prayer navigation regression'); excluded=prayer.get('excludedMetadata',{}); require(excluded.get('dateBars')==2 and excluded.get('specialBars')==1 and all(x.get('he') and x.get('he_nikud') and x.get('en') and 'עברית ▾' not in x['en'] and 'Cheshvan' not in x['he'] and 'רֹאשׁ הַשָּׁנָה' not in x['he'] for x in qsegs),'Prayer blocks/bar metadata mismatch')
 nanach=load(BASE/'likutay-nanach.json'); nsegs=nanach.get('segments',[]); expected_nanach=[(name,i) for name,first,last in RANGES for i in range(first,last+1)]; require(len(nsegs)==33 and [x['index'] for x in nsegs]==list(range(1,34)) and [(x.get('sourceFile'),x.get('sourceIndex')) for x in nsegs]==expected_nanach and nanach.get('hasEnglish') is False and all(x.get('he') and not x.get('en') for x in nsegs),'Nanach seven-file Hebrew-only range mismatch')
 nanach_source=ROOT/'public/reader/likutay-nanach/volume-4'; require(load(nanach_source/'chapter-18.json')['segments'][52]['he'].strip()=='תורה כב חותם בתוך חותם' and load(nanach_source/'chapter-25.json')['segments'][12]['he'].strip()=='תורה כג','Nanach semantic headings changed')
 registry=load(ROOT/'src/data/lm-commentaries.json'); assoc22=registry['1']['22']['related_commentaries']; assoc21=registry['1']['21']['related_commentaries']; n_assoc=[x for x in assoc22 if x.get('book')=='likutay-nanach']; b_assoc=[x for x in assoc22 if x.get('book')=='biur-halikutim']; require(len(n_assoc)==1 and n_assoc[0].get('url')=='/reader/super/likutay-moharan/1/22/likutay-nanach.json' and n_assoc[0].get('sourceRanges')==[{'file':f,'startIndex':a,'endIndex':b,'count':b-a+1} for f,a,b in RANGES] and n_assoc[0].get('totalRecords')==33 and 'chapter 26 is unrelated' in n_assoc[0].get('superReaderBoundaryNote',''),'Nanach discovery association mismatch'); require(len(b_assoc)==1 and b_assoc[0].get('url')=='/reader/super/likutay-moharan/1/22/biur-halikutim.json' and b_assoc[0].get('sourceRange')=={'startIndex':143,'endIndex':210,'count':68},'Biur discovery association mismatch'); require(any(x.get('book')=='biur-halikutim' and x.get('url')=='/reader/biur-halikutim/1/26' for x in assoc21),'Torah 21 shared Biur discovery changed')
 manifest=load(BASE/'peer-halikutim/manifest.json'); pages=manifest.get('pages',[]); require(manifest.get('hebrewBooksId')==66038 and manifest.get('sourceSha256')==SHA and manifest.get('sourcePageRange')==[413,516] and len(pages)==104 and [x['sourcePage'] for x in pages]==list(range(413,517)),'Pe’er constants/range mismatch'); require(manifest.get('pdf')=='/reader/super/likutay-moharan/1/22/peer-halikutim/peer-halikutim-torah-22.pdf' and all(x.get('image')==f'/reader/super/likutay-moharan/1/22/peer-halikutim/page-{x["sourcePage"]}.webp' for x in pages),'Pe’er public paths mismatch'); require('page 412 is Torah 21' in manifest.get('textNotice','') and 'page 517 begins appendices' in manifest.get('textNotice','') and all('page-412.webp' not in x.get('image','') and 'page-517.webp' not in x.get('image','') for x in pages),'Pe’er exclusions mismatch')
 expected_assets={f'page-{n}.webp' for n in range(413,517)}; actual_assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')}; pdf_ready=(BASE/'peer-halikutim/peer-halikutim-torah-22.pdf').is_file(); require((not actual_assets and not pdf_ready) or (actual_assets==expected_assets and pdf_ready),'Pe’er asset readiness mismatch'); require(not args.pending_facsimiles or (not actual_assets and not pdf_ready and manifest.get('facsimileStatus')=='pending-separately-supervised-conversion'),'Explicit pending mode requires no facsimile artifacts and pending manifest')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/22.astro').read_text(encoding='utf-8'); layers=set(re.findall(r'data-open-source="([^"]+)"',astro)); require(layers=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},f'Expected nine study layers, got {sorted(layers)}')
 for token in ('<span><b>9</b> study layers</span>','exactly 124 Hebrew leaves','22:13:1','shifted 27 legacy Classic alignments','beginner English-only','section 26 physical indices 143–210','source section 23 · 27 Hebrew-only records','33 substantive Hebrew-only records','17 bilingual blocks p22a–p22q','Pe’er pages 413–516','page 517 begins appendices','https://www.peer-halikutim.com/'):
  require(token in astro,f'Route source-integrity token missing: {token}')
 classic_page=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(encoding='utf-8-sig').replace('\x00',''); part_directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(encoding='utf-8-sig').replace('\x00',''); book_directory=(ROOT/'src/pages/reader/likutay-moharan/index.astro').read_text(encoding='utf-8-sig').replace('\x00',''); require(classic_page.count('[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]')>=2 and '/reader/super/likutay-moharan/1/${torahNum}' in classic_page,'Classic route text/launch integration missing'); require('Array.from({ length: 22 }' in part_directory and 'Number(item.number) <= 22' in part_directory and '/reader/super/likutay-moharan/1/${number}' in part_directory,'Part directory discovery upper bound missing'); require("Astro.redirect('/reader/likutay-moharan/1/'" in book_directory,'Book directory redirect changed')
 status='facsimiles pending separately supervised conversion' if not actual_assets else 'facsimiles ready'; print('Validated Torah 22: 124 bilingual leaves across 21 sections, exact 27-Classic crosswalk and editorial anomalies, 30 phrases, 9 layers, Pettek 27 asymmetric, Biur 68 with Torah 21 shared source intact, Parparos 27 Hebrew-only, Nanach 33, prayer 17, Pe’er pages 413–516; '+status+'.')
if __name__=='__main__': main()
