#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 32 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/32'; SHA='f831b7a589474499ea1e6b7241ee0a5ed1b910148324449210209760a48792b7'; AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
def load(p): return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',v or '')).strip()
def req(c,m):
 if not c: raise RuntimeError(m)
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--pending-facsimiles',action='store_true'); a=ap.parse_args(); study=load(BASE/'torah-study.json'); s=study['segments']; refs=[f'Likutei Moharan 32:1:{i}' for i in range(1,8)]
 req(len(s)==7 and [z['index'] for z in s]==list(range(1,8)) and [z['sourceRef'] for z in s]==refs,'7 exact records/refs'); req(all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in s),'bilingual witness'); req(study['productionAlignedPassages']==study['productionDisplayRecords']==study['sefariaPassages']==7 and study['sefariaSectionCounts']==[7] and study['restoredBilingualSupplements']==study['structuralRestorations']==0,'counts')
 src=study['source']; req(src['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and src['license']=='CC-BY-NC' and src['versionSource']=='https://www.nli.org.il/he/books/NNL01','English license'); req(src['heVersionTitle']=='Likutei Moharan - rabenubook.com' and src['heLicense']=='Public Domain' and src['prev']=='Likutei Moharan 31:18' and src['lastNext']=='Likutei Moharan 33:1','Hebrew license/bounds'); req('לשון רבנו זכרונו לברכה' in plain(s[0]['he']) and 'Adonoy Sfatai' in plain(s[0]['en']) and 'Leah' in plain(s[-1]['en']),'anchors'); req(s[0]['classicSegments']==[1,2] and s[0]['classicSegment']==2 and all(z['classicSegments']==[2] for z in s[1:]),'classic crosswalk')
 ph=load(BASE/'phrase-study.json'); req(len(ph['phrases'])==30 and ph['selectedPassages']==list(range(1,8)) and ph['representedSections']==[1],'30 phrases/all leaves')
 for x in ph['phrases']:
  z=s[x['segment']-1]; req(x['source']==x['sourceRef']==z['sourceRef'] and x['he'] in plain(z['he']) and x['enMatch'] in plain(z['en']),'phrase provenance/text'); req(all(f'data-inline-phrase="{x["id"]}"' in z[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-32.json'); req(len(p['segments'])==2 and p['layerAvailability']==AV and [z['alignedPassages'] for z in p['segments']]==[[1],list(range(1,8))],'Pettek crosswalk'); req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek truth')
 for name in ('biur-halikutim','parparos-lechochma'):
  d=load(BASE/f'{name}.json'); req(d['segments']==[] and d['totalSegments']==0 and d['availability']=='unavailable',f'{name} unavailable')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-32.json'); req(len(prayer['segments'])==1 and prayer['assignedPackageIds']==['p32a'] and prayer['navigation']['prevUrl'] and prayer['navigation']['nextUrl'] and prayer['excludedMetadata']['dateBars']==1,'prayer schema'); req(prayer['segments'][0]['he'].startswith('אֲדֹנָי שְׂפָתַי') and prayer['segments'][0]['en'].startswith('My Lord, open my lips') and 'עברית ▾' not in prayer['segments'][0]['en'],'prayer content'); req((ROOT/'public/teachings/likutay-tefilos/likutay_tefilos_32_33_34_prayers32_33_34.html').is_file(),'prayer HTML')
 nn=load(BASE/'likutay-nanach.json'); req(len(nn['segments'])==10 and [z['sourceIndex'] for z in nn['segments']]==list(range(68,78)) and all(z['he'] and not z.get('en') for z in nn['segments']) and nn['excludedHeadings']==[{'file':'volume-4/chapter-26.json','index':67},{'file':'volume-4/chapter-26.json','index':78}],'Nanach bounds'); rel=load(ROOT/'src/data/lm-commentaries.json')['1']['32']['related_commentaries']; nr=[z for z in rel if z.get('book')=='likutay-nanach']; req(len(nr)==1 and nr[0]['totalRecords']==10 and nr[0]['url'].endswith('/32/likutay-nanach.json') and not [z for z in rel if z.get('book')=='parparos-lechochma'],'registry')
 m=load(BASE/'peer-halikutim/manifest.json'); req(m['sourceSha256']==SHA and m['hebrewBooksId']==66040 and m['sourcePageRange']==[352,362] and [z['sourcePage'] for z in m['pages']]==list(range(352,363)),'Pe’er range'); assets={x.name for x in (BASE/'peer-halikutim').glob('page-*.webp')}; expected={f'page-{x}.webp' for x in range(352,363)}; pdf=(BASE/'peer-halikutim/peer-halikutim-torah-32.pdf').is_file(); req(not (BASE/'peer-halikutim/page-351.webp').exists() and not (BASE/'peer-halikutim/page-363.webp').exists(),'excluded assets')
 if a.pending_facsimiles: req(not assets and not pdf and m['facsimileStatus'].startswith('pending'),'pending facsimiles')
 else: req(assets==expected and pdf and m['facsimileStatus']=='ready','facsimiles ready')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/32.astro').read_text(); req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers'); req('exactly 7 bilingual leaves' in astro and 'pages 352–362' in astro and 'Biur and Parparos are unavailable' in astro and '10 substantive Hebrew-only' in astro and '1 authoritative paired bilingual block' in astro and 'https://www.peer-halikutim.com/' in astro,'route truth/credit')
 classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(); directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(); req(classic.count('29, 30, 31, 32]')>=2 and 'length: 32' in directory and '<= 32' in directory and "'כט','ל','לא','לב'" in directory,'discovery')
 print('Validated Torah 32: 7 exact bilingual leaves, 30 phrases, 9 layers, Pettek 2 asymmetric, Biur/Parparos unavailable, Nanach 10 HE-only, prayer 1 bilingual, Pe’er 352–362; '+('facsimiles pending separately supervised conversion.' if a.pending_facsimiles else 'facsimiles ready.'))
if __name__=='__main__': main()
