#!/usr/bin/env python3
"""Strict targeted verifier for audited Torah 30 Super Reader."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'public/reader/super/likutay-moharan/1/30'; SHA='f831b7a589474499ea1e6b7241ee0a5ed1b910148324449210209760a48792b7'; COUNTS=[8,4,12,4,7,13,9,10,12,3]
AV={'beginner':{'he':False,'en':True},'intermediate':{'he':True,'en':True},'scholarly':{'he':True,'en':False}}
EXPECTED={1:list(range(1,6)),2:[6],3:[7],4:[8,9],5:list(range(10,14)),6:list(range(14,19)),7:list(range(19,22)),8:list(range(22,26)),9:list(range(26,30)),10:list(range(30,37)),11:list(range(37,50)),12:list(range(50,59)),13:list(range(59,69)),14:list(range(69,80)),15:[80],16:list(range(81,84))}
def load(p): return json.loads(Path(p).read_text(encoding='utf-8-sig').replace('\x00',''))
def plain(v): return re.sub(r'\s+',' ',re.sub(r'</?span[^>]*>','',v or '')).strip()
def req(c,m):
 if not c: raise RuntimeError(m)
def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--pending-facsimiles',action='store_true'); args=parser.parse_args(); study=load(BASE/'torah-study.json'); segs=study['segments']; refs=[f'Likutei Moharan 30:{s}:{l}' for s,n in enumerate(COUNTS,1) for l in range(1,n+1)]
 req(len(segs)==83 and [z['index'] for z in segs]==list(range(1,84)),'83 display records'); paired=[z for z in segs if isinstance(z.get('sourceComment'),int)]; req([z['sourceRef'] for z in paired]==refs,'exact Sefaria refs'); req(len(paired)==82 and all(plain(z['he']) and plain(z['en']) and plain(z['he'])!=plain(z['en']) for z in paired),'bilingual witness invariant'); req(study['productionAlignedPassages']==82 and study['productionDisplayRecords']==83 and study['sefariaPassages']==82 and study['sefariaSectionCounts']==COUNTS and study['restoredBilingualSupplements']==0 and study['structuralRestorations']==1,'counts')
 source=study['source']; req(source['versionTitle']=='Likutey Moharan Volumes 1-11, trans. by Moshe Mykoff. Breslov Research Inst., 1986-2012' and source['license']=='CC-BY-NC' and source['versionSource']=='https://www.nli.org.il/he/books/NNL01','English license'); req(source['heVersionTitle']=='Likutei Moharan - rabenubook.com' and source['heLicense']=='Public Domain' and source['prev']=='Likutei Moharan 29:12' and source['lastNext']=='Likutei Moharan 31:1','Hebrew license/boundaries'); req(segs[0]['sourceRef']=='Likutei Moharan 30:1:1' and segs[-1]['sourceRef']=='Likutei Moharan 30:10:3' and 'מישרא דסכינא' in plain(segs[0]['he']),'anchors'); req(segs[5]['sourceRef']=='Classic Torah 30 physical segment 2' and segs[5]['supplementType']=='hebrew-only-classic-rashi-structural-restoration' and plain(segs[5]['he']).startswith('רש"י: במאי קטלי לה') and not segs[5]['en'],'Classic restoration')
 by={i:[z['index'] for z in segs if int(z['classicSegment'])==i] for i in range(1,17)}; req(by==EXPECTED,'classic crosswalk')
 phrases=load(BASE/'phrase-study.json'); req(len(phrases['phrases'])==30 and phrases['representedSections']==list(range(1,11)),'30 phrases/10 sections'); req(len(phrases['selectedPassages'])==10 and len(set(phrases['selectedPassages']))==10,'selected passages')
 for phrase in phrases['phrases']:
  seg=segs[int(phrase['segment'])-1]; req(phrase['source']==phrase['sourceRef']==seg['sourceRef'],'phrase provenance'); req(phrase['he'] in plain(seg['he']) and phrase['enMatch'] in plain(seg['en']),'exact phrase text'); req(all(f'data-inline-phrase="{phrase["id"]}"' in seg[k] for k in ('he','he_nikud','en')),'phrase sync')
 p=load(ROOT/'public/reader/pettek-nanach-commentary/torah-30.json'); req(len(p['segments'])==16 and p['layerAvailability']==AV,'Pettek count/availability'); req([z['alignedPassages'] for z in p['segments']]==[EXPECTED[i] for i in range(1,17)],'Pettek crosswalk'); req(all({layer:{lang:bool(str((z['layers'].get(layer) or {}).get(lang) or '').strip()) for lang in ('he','en')} for layer in AV}==AV for z in p['segments']),'Pettek language truth')
 biur=load(BASE/'biur-halikutim.json'); req(len(biur['segments'])==85 and [z['sourceIndex'] for z in biur['segments']]==list(range(1,86)) and all(z['he'] and not z.get('en') for z in biur['segments']) and biur['availability']=='hebrew-only' and biur['nextTorahHeadingIndex']==86,'Biur 85 HE-only'); par=load(BASE/'parparos-lechochma.json'); pi=list(range(2,31,2)); req(len(par['segments'])==15 and par['sourceIndices']==pi and all(z['he'] and not z.get('en') for z in par['segments']) and par['availability']=='hebrew-only','Parparos 15 HE-only')
 prayer=load(ROOT/'public/reader/likutay-tefilos/part-1/prayer-30.json'); req(len(prayer['segments'])==17 and [z['sourceId'] for z in prayer['segments']]==[f'p30{chr(97+i)}' for i in range(17)] and prayer['navigation']['prevUrl'] and prayer['navigation']['nextUrl'] and prayer['excludedMetadata']['dateBars']==5 and all(z['he'] and z['en'] and 'עברית ▾' not in z['en'] for z in prayer['segments']),'authoritative prayer')
 html_path=ROOT/'public/teachings/likutay-tefilos/likutay_tefilos_30_prayer30.html'; req(html_path.is_file(),'copied authoritative prayer HTML')
 nn=load(BASE/'likutay-nanach.json'); sis=list(range(185,222)); req(len(nn['segments'])==37 and [z['sourceIndex'] for z in nn['segments']]==sis and all(z['he'] and not z.get('en') for z in nn['segments']) and nn['excludedHeadings']==[184,222],'bounded Nanach'); related=load(ROOT/'src/data/lm-commentaries.json')['1']['30']['related_commentaries']; nr=[z for z in related if z.get('book')=='likutay-nanach']; req(len(nr)==1 and nr[0]['sourceIndices']==sis and nr[0]['url'].endswith('/30/likutay-nanach.json'),'registry')
 manifest=load(BASE/'peer-halikutim/manifest.json'); req(manifest['sourceSha256']==SHA and manifest['hebrewBooksId']==66040 and manifest['sourcePageRange']==[135,237] and [z['sourcePage'] for z in manifest['pages']]==list(range(135,238)),'Pe’er range'); assets={p.name for p in (BASE/'peer-halikutim').glob('page-*.webp')}; expected_assets={f'page-{x}.webp' for x in range(135,238)}; pdf=(BASE/'peer-halikutim/peer-halikutim-torah-30.pdf').is_file(); req(not (BASE/'peer-halikutim/page-134.webp').exists() and not (BASE/'peer-halikutim/page-238.webp').exists(),'excluded pages absent')
 if args.pending_facsimiles: req(not assets and not pdf and manifest['facsimileStatus'].startswith('pending'),'pending facsimiles')
 else: req(assets==expected_assets and pdf and manifest['facsimileStatus']=='ready','facsimiles ready')
 astro=(ROOT/'src/pages/reader/super/likutay-moharan/1/30.astro').read_text(encoding='utf-8'); req(set(re.findall(r'data-open-source="([^"]+)"',astro))=={'phrase','guide','pettek','biur','parparos','nanach','prayer','peer','notes'},'nine layers'); req('82 bilingual leaves across sections 30:1–10' in astro and 'pages 135–237' in astro and 'https://www.peer-halikutim.com/' in astro and '85 Hebrew-only' in astro and '15 Hebrew-only' in astro and '17 paired bilingual blocks' in astro,'route truth/credit')
 classic=(ROOT/'src/pages/reader/likutay-moharan/[part]/[torah].astro').read_text(encoding='utf-8'); directory=(ROOT/'src/pages/reader/likutay-moharan/[part]/index.astro').read_text(encoding='utf-8'); req(classic.count('28, 29, 30]')>=2 and 'length: 30' in directory and '<= 30' in directory and "'כח','כט','ל'" in directory,'discovery')
 print('Validated Torah 30: 82 exact bilingual leaves + 1 Hebrew-only Classic Rashi restoration (83 records), 30 phrases across 10 sections, 9 layers, Pettek 16 asymmetric, Biur 85 HE-only, Parparos 15 HE-only, Nanach 37 HE-only, prayer 17, Pe’er 135–237; '+('facsimiles pending separately supervised conversion.' if args.pending_facsimiles else 'facsimiles ready.'))
if __name__=='__main__': main()
